### ISSUE TITLE
Enable running workflows in the web UI

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#1]
- [x] Run workflows via GET, pass data, flux, and fix
- [x] Run workflows with sample data and flux from editor
- [x] Display workflow output
- [x] Set up input fields for data & flux
- [ ] Integrate flux editor (&rarr; [new issue](https://github.com/metafacture/metafacture-fix/issues/new))

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/fix

**Comment by acka47** [comment]
+1
