### ISSUE TITLE
Consolidate path traversal.

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#102]
Also, `transformFields()` and `find()`/`findNested()` are basically performing the same traversal operations. There may be room for consolidation.

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/issues/97#issuecomment-998095139_

For now, I'm getting a bit uneasy about the divergence of object traversal between `find()`/`insert()` and `transformFields()`. I should probably work on that next.

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/pull/98#pullrequestreview-838593348_

Right, this is also where I'm currently at in #95, where certain things only work in a bind if we first do e.g. an `upcase` (which calls `transformFields`).

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/issues/98#issuecomment-1000266444_

**Comment by blackwinter** [comment]
In addition to keeping our internal code consistent, we should probably also adopt a model similar to [Catmandu's](https://metacpan.org/pod/Catmandu::Path::simple) with designated `getter`s/`setter`s/`creator`s/etc.

Currently, we can't [properly](https://github.com/metafacture/metafacture-fix/blob/1eebaac79dd177c765e4a4a9f5aea6d118e8d183/metafix/src/test/java/org/metafacture/metafix/MetafixMethodTest.java#L1251) [deal](https://github.com/metafacture/metafacture-fix/blob/f1fcf993d11bb03102620816abc2479bb16390ff/metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java#L427) [with](https://github.com/metafacture/metafacture-fix/blob/1eebaac79dd177c765e4a4a9f5aea6d118e8d183/metafix/src/test/java/org/metafacture/metafix/MetafixRecordTest.java#L1863) [wildcards](https://github.com/metafacture/metafacture-fix/commit/7d9b2a44017117469fcc46140048416877da017f#diff-25b98d43ad1210c8ef1168013b98f9724d1d5b4205a911ba146f4bdfebb32a9b) when inserting/transforming values (see also #92 and #100). This needs to be fixed somehow, quite possibly by introducing an abstract path traversal model.

**Comment by fsteeg** [comment]
Merging #133 would unblock work on #113 & #116 (which will touch the same code). Note (mostly to self): continue by making the second FixPath constructor private, work on `Hash.appendValue` / `modifyFields` (as mentioned in our meeting, I'll only be able to continue here at the end of next week).

**Comment by TobiasNx** [comment]
Added integration tests derived from testing with OERSI: https://github.com/metafacture/metafacture-fix/pull/199
At the moment none of the workflows runs through. Mostly because of the lookup-routines that we have, some behaviour with asterisks and problems with manipulating stuff in newly generated arrays. When comment the stuff in the oersi workflows out they seem to work. Except for TIB AV which has errors that I do not understand.
