### ISSUE TITLE
Strange behaviour moving generated arrays and successively generating arrays into nested structure

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#113]
move_field and copy_field seem to have problems moving generated arrays and generating arrays into nested structures.

**Moving**
- _moving_ a generated array **with a single value** is transformed into an simple string-array
- _moving_ a generated array **with a multiple values** is working

**Generating**
- _generating_ an array **with a multiple values**  into an nested object is  transformed into an array with an object indexing all values as own elements
- _generating_ an array **with a single value**  into an nested object is working

- _generating or  moving_ an array into an object of an array is breaking or not working

--- was originally:----
When moving an array in an object of arrays the behavior seems strange.
If you move an array into an object of array the behavior seems okay.

See testcase here: 

https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/move_field_in_object_array
https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/copy_array

**Comment by fsteeg** [comment]
To avoid conflict with #102, should be started after the planned first PR for #102.

Functional review: @TobiasNx
Code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
Some behaviour seems to be solved.

**Comment by blackwinter** [comment]
Pending integration test:

- [copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldArrayOfObjectsAndListNewArrayOfObjectsAndMoveSubfield)
