### ISSUE TITLE
vacuum does not work on empty arrays and empty objects

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#114]
[See example here](https://metafacture.org/playground/?flux=PG_DATA%0A%7Cas-records%0A%7Cdecode-json%0A%7Cfix%0A%7Cencode-json%0A%7Cprint%0A%3B&fix=vacuum%28%29&data=%7B%0A%22id%22%3A+%22https%3A//open.ruhr-uni-bochum.de/lernangebot/uebung-fuer-fortgeschrittene-tod-und-raum%22%2C%0A%22name%22%3A+%5B%5D%2C%0A%22type%22%3A+%7B%7D%2C%0A%22kind%22%3A+%22%22%0A%7D&active-editor=fix)

**Comment by blackwinter** [comment]
Functional review: @TobiasNx 
Code review: @fsteeg

**Comment by TobiasNx** [comment]
looks good +1
