### ISSUE TITLE
Conditional `any_equal` not working correctly with path wildcards.

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#115]
When using path wildcards (#89) to select multiple subfields, `any_equal` fails to match any of them (see 8777ffd for unit tests, and [Limetrans](https://github.com/hbz/limetrans/commit/b595fbbba5fbdb3a0cccaaa0cd4fb496f3ea6db2#diff-39fb43e4ba2206cf8b1e62f5dfd8457c8714d288ad298609e752e09246b777edR211-R228) for a real-world use case).

**Comment by blackwinter** [comment]
Also, there's a case to be made that alternations don't work as intended: `data.name|data.nome` will be split into `data`, `name|data` and `nome` instead of `data.name` and `data.nome`. Which is why the nested tests don't fail.

**Comment by blackwinter** [comment]
Seems to be the same underlying cause as #119: `IllegalStateException: expected String, got Array` (when requiring value to be a string instead of converting it to a string: `asString()` vs. `toString()`).

**Comment by fsteeg** [comment]
Functional review: @TobiasNx
Code review: @fsteeg

**Comment by TobiasNx** [comment]
Seems to work with the changes if it is on a simple top level but does not seem to work as part of `do list`.

**Comment by blackwinter** [comment]
> does not seem to work as part of `do list`.

The path is wrong, must be `person[]`.

Also, there's an extra curly bracket in `expected.json`: `"person" : [ {{`

**Comment by blackwinter** [comment]
@TobiasNx approved in [#142 (comment)](https://github.com/metafacture/metafacture-fix/pull/142#issuecomment-1039007562).
