### ISSUE TITLE
Default behaviour of `copy_field`/`move_field`/`add_field` should be destructive, the appending behaviour creates problems

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#116]
[See here](https://metafacture.org/playground/?flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22string2%22%2C%22string%22%29%0Amove_field%28%22string3%22%2C%22string%22%29%0Aadd_field%28%22string%22%2C%22string4%22%29&data=%7B%0A++++%22string%22%3A%22string%22%2C%0A++++%22string2%22%3A+%22string2%22%2C%0A++++%22string3%22%3A+%22string3%22%0A%7D&active-editor=fix)
(The error seems to be not virulent any more, but the underlying behaviour is still productive.)

Catmandu Fix default behaviour is destructive

Appending should only be done explicitly and copy/move/add_field should be destructive.
Could be that this is the root of #113 

- [x] `add_field` (#308)
- [x] `copy_field` (#313)
- [x] `move_field` (#313)

**Comment by blackwinter** [comment]
Catmandu is destructive: hbz/Catmandu@4d2f0e3.

**Comment by fsteeg** [comment]
To avoid conflict with #102, should be started after the planned first PR for #102.

Functional review: @TobiasNx
Code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
Since this is standard behaviour of Catmandu fix I bump this.

**Comment by TobiasNx** [comment]
Since this is standard behaviour of Catmandu fix I bump this.

**Comment by blackwinter** [comment]
@TobiasNx: `add_field()` behaviour is going to be changed with #308. Please test it.

**Comment by TobiasNx** [comment]
> @TobiasNx: `add_field()` behaviour is going to be changed with #308. Please test it.

@blackwinter tested it. seems to work :) +1

**Comment by blackwinter** [comment]
- [ ] `add_field`
- [ ] `copy_field`
- [ ] `move_field`

**Comment by blackwinter** [comment]
@TobiasNx: `copy_field()`/`move_field()` behaviour is going to be changed with #313. Please test it.

**Comment by blackwinter** [comment]
> tested different variations.

Thanks, but just to be sure: Have you also verified that your current transformations (lobid-resources, oersi, etc.) are going to work with these changes? If not, do you maybe want to do it before we merge?

**Comment by TobiasNx** [comment]
+1
