### ISSUE TITLE
Facilitate composability (file inclusion)

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#12]
* Allow Fixes to include other Fix files (cf. [Metamorph: Splitting Metamorph Definitions for Reuse](https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide#splitting-metamorph-definitions-for-reuse)).
* Included files are evaluated in-place at the time of inclusion.
* Possibly allow parameters to be passed to the included file.

```
include(path_to_fix, params...)
```

**Comment by TobiasNx** [comment]
One question, is this a combination of the macro and include because of the parameters?

**Comment by TobiasNx** [comment]
Anyway to make the path "flexible"? Similar to FLUX_DIR, something as FIX-DIR?

**Comment by TobiasNx** [comment]
simple include works

**Comment by blackwinter** [comment]
> One question, is this a combination of the macro and include because of the parameters?

Not intentionally, no. The only parameter currently recognised is the path.

**Comment by blackwinter** [comment]
> Anyway to make the path "flexible"? Similar to FLUX_DIR, something as FIX-DIR?

That's what's currently emulated with the `.` syntax (`./path/to.fix` refers to `$FIX_DIR/path/to.fix`, while `path/to.fix` refers to `$PWD/path/to.fix`). But I concede that it's a bit obscure. Should we rather inject a variable into the script instead of treating a leading `.` specially? (so `$[FIX_DIR]/path/to.fix` instead of `./path/to.fix`)

Catmandu has the concept of an "include path", which I didn't feel the urge to implement yet (due to its - currently unneeded - complexity). If we had implemented it, we could simply add `PWD` and `FIX_DIR` to it (so you could use `path/to.fix` either way, which would then resolve to whichever file is found first).
