### ISSUE TITLE
Add `flatten`-function

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#122]
Flatten is not added as function.
It can be helpful if we have an array of keywords with some keywords connected and some tokenized.

in:
```
{
	"keywords": [
		"dog",
		"cat",
		"horse,bird,dragon"
	]
}
```

If we would split the third keyword we would (which we cannot at the moment) we would get an array in an array. Then `flatten` would be nice.

result (does not work yet because of the asterisk-problem with spli-field):
```
{
	"keywords": [
		"dog",
		"cat",
		["horse" , "bird" , "dragon"]
	]
}
```
should:
```
{
	"keywords": [
		"dog",
		"cat",
		"horse",
		"bird",
		"dragon"
	]
}
```

See test-scenario:
https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/flattening

**Comment by blackwinter** [comment]
Related to #100.

**Comment by fsteeg** [comment]
Will revisit after https://github.com/metafacture/metafacture-fix/issues/121.
