### ISSUE TITLE
Error-Response - ideas

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#123]
For users error-responses like that:

`org.metafacture.framework.MetafactureException: java.lang.IllegalStateException: expected String, got Hash`

do not help understanding where the error is in the fix.

It should state the function, ideally also the line in the fix.

**Comment by fsteeg** [comment]
We need at least the function name, ideal would be line and column in fix file/input.

Functional review: @TobiasNx
Code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
+1 looks good :)

**Comment by blackwinter** [comment]
More often than not, it might be useful (or even necessary) to relate the error to the current record. In case anybody has an idea as to how we could transport the failed record to the user, please speak up. (And no, simply appending it to the error message is probably not the way to go...)

**Comment by dr0i** [comment]
> simply appending it to the error message is probably not the way to go.

Why not? If you fear bloated log messages you may want to make use of log levels, say append whole record when set to `debug`.
