### ISSUE TITLE
Missing "end" results in copying the whole input data instead of error

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#126]
https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/41e403a51e4a987192f27fd246c67c24725119b9/data/testing/missingErrorWhenTrailingEndIsMissing

instead of an error, a missing end results in passing through all input data.

Expected: error
Is: input-file

**Comment by blackwinter** [comment]
Related to (or even duplicate of) #79?

**Comment by TobiasNx** [comment]
Yes related and or duplicated, therefore we decided off board to close this and solve it  in #79
