### ISSUE TITLE
Generating new arrays with `$append`/`$prepend`

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#127]
We should reintroduce $append and $prepend as creation methods if the array does not exist in a record to add to or create an array.

Was part of: https://github.com/metafacture/metafacture-fix/issues/111
Related to: #93  and #92

**Comment by fsteeg** [comment]
Will revisit after #102.

**Comment by blackwinter** [comment]
Integration tests:

- [add_fieldAppendAndCreateArrayOfObjectsInArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAppendAndCreateArrayOfObjectsInArrayOfObjects)
- [add_fieldAppendAndCreateArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAppendAndCreateArrayOfObjects)
- [add_fieldAppendAndCreateArrayOfStringsInArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAppendAndCreateArrayOfStringsInArrayOfObjects)
- [add_fieldAppendAndCreateArrayOfStrings](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAppendAndCreateArrayOfStrings)
- [add_fieldAppendAndCreateNestedArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAppendAndCreateNestedArrayOfObjects)
- [add_fieldAppendAndCreateNestedArrayOfStrings](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldAppendAndCreateNestedArrayOfStrings)
- [add_fieldPrependAndCreateArray](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/add_fieldPrependAndCreateArray)
- [copy_fieldAppendAndCreateArrayOfObjectsInArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAppendAndCreateArrayOfObjectsInArrayOfObjects)
- [copy_fieldAppendAndCreateArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAppendAndCreateArrayOfObjects)
- [copy_fieldAppendAndCreateArrayOfStringsInArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAppendAndCreateArrayOfStringsInArrayOfObjects)
- [copy_fieldAppendAndCreateArrayOfStrings](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAppendAndCreateArrayOfStrings)
- [copy_fieldAppendAndCreateNestedArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAppendAndCreateNestedArrayOfObjects)
- [copy_fieldAppendAndCreateNestedArrayOfStrings](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldAppendAndCreateNestedArrayOfStrings)
- [copy_fieldPrependAndCreateArray](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldPrependAndCreateArray)
- [move_fieldAppendAndCreateArrayOfObjectsInArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAppendAndCreateArrayOfObjectsInArrayOfObjects)
- [move_fieldAppendAndCreateArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAppendAndCreateArrayOfObjects)
- [move_fieldAppendAndCreateArrayOfStringsInArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAppendAndCreateArrayOfStringsInArrayOfObjects)
- [move_fieldAppendAndCreateArrayOfStrings](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAppendAndCreateArrayOfStrings)
- [move_fieldAppendAndCreateNestedArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAppendAndCreateNestedArrayOfObjects)
- [move_fieldAppendAndCreateNestedArrayOfStrings](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldAppendAndCreateNestedArrayOfStrings)
- [move_fieldPrependAndCreateArray](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldPrependAndCreateArray)

**Comment by TobiasNx** [comment]
It seems that this would "only" need adjustment in two code segments, but I could be wrong:

https://github.com/metafacture/metafacture-fix/blob/55617299f2a8e203ffc6816cbce96c7a57416eb6/metafix/src/main/java/org/metafacture/metafix/FixPath.java#L173-L175

https://github.com/metafacture/metafacture-fix/blob/55617299f2a8e203ffc6816cbce96c7a57416eb6/metafix/src/main/java/org/metafacture/metafix/FixPath.java#L342-L345

**Comment by fsteeg** [comment]
Ready for functional review in branch `127-arrays`.

**Comment by fsteeg** [comment]
Changes in PR should be done, could you test again with current branch `127-arrays`?

**Comment by TobiasNx** [comment]
I tried lobid-resources and all tests did run trough without changes +1
