### ISSUE TITLE
Facilitate extensibility (polyglot programming)

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#14]
* Allow functions to be defined in other languages than Fix (e.g. Java and/or JavaScript; cf. [Metamorph: Integration of Java and JavaScript](https://github.com/metafacture/metafacture-core/wiki/Integration-of-Java-and-JavaScript)).
* Might require an import mechanism in order to make those functions available (see #13).

**Comment by blackwinter** [comment]
Can we make this "ready"? I'd like to work on it next, specifically the Java integration; JavaScript integration and import mechanism not needed (yet).

**Comment by fsteeg** [comment]
> Can we make this "ready"? I'd like to work on it next, specifically the Java integration;

Would it make sense for @dr0i to do functional review here? I can do code review.

If @dr0i agrees, this should be ready then.

**Comment by blackwinter** [comment]
> Would it make sense for @dr0i to do functional review here?

If that's possible, sure. Otherwise, I can do it with Limetrans (adapt [`hbz.limetrans.metamorph.ZDB`](https://github.com/hbz/limetrans/blob/master/src/main/java/hbz/limetrans/metamorph/ZDB.java) to be usable from Fix).

**Comment by dr0i** [comment]
I could also give it a try and btw. learn about using fix. Just go on @blackwinter .

**Comment by blackwinter** [comment]
Functional review: @dr0i
Code review: @fsteeg

**Comment by blackwinter** [comment]
I'm always having trouble with the Xtext documentation :disappointed: @fsteeg: Do you happen to know where I can find the definition of `ValidID`?

**Comment by fsteeg** [comment]
> Do you happen to know where I can find the definition of ValidID?

It seems to be defined as `'^'? ('a'..'z'|'A'..'Z'|'$'|'_') ('a'..'z'|'A'..'Z'|'$'|'_'|'0'..'9')*;` in `/org/eclipse/xtext/xbase/Xtype.xtext` (org.eclipse.xtext.xbase-2.17.0.jar).

**Comment by blackwinter** [comment]
Thanks. So [use the source](https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/Xtype.xtext#L81), I guess...

It's just that I was under the assumption that qualified names were already allowed as function names, but I had to change `ValidID` to `QualifiedName`. So I wanted to know what `ValidID` actually is.

**Comment by dr0i** [comment]
Sorry @blackwinter , I had several days off and have to admit to not have any time to review this.

> If that's possible, sure. Otherwise, I can do it with Limetrans (adapt hbz.limetrans.metamorph.ZDB to be usable from Fix).

Better you do the review as proposed.
