### ISSUE TITLE
Fix-Path - Command or Function?

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#147]
With the changes of https://github.com/metafacture/metafacture-fix/pull/131 it is not possible to emit the FIX internal path-structure.
While I still agree with all the changes it makes it more difficult to recreate the path-structure which is internal to fix.

For JSON/YAML this is no problem, since the flux-structure after the fix and the internal path-structure are the same.

For all formats that have repeated fields, that need dot-path refrences I cannot get possible index-numbers.

See: 
https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/master/data/testing/alma_structure/xml-structure.flux

Was:
https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/e271ce1f84d55a69e4aba67814ea663841f19437/data/testing/alma_structure/structure.txt

Now is:
https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/master/data/testing/alma_structure/structure.txt

This makes it difficult to grasp the correct path if there are repeated fields and where to add the index-numbers or arrays-wildcards.

`i.am.1.a.2.Path` in FIX would be `i.am.a.Path ` outside the FIX. 

I propose a FLUX-Function that just emits the FIX-Paths.
This would help to find path quickly.

**Comment by TobiasNx** [comment]
one solution could be a slimed version of the fix at the status of https://github.com/metafacture/metafacture-fix/pull/131,
That just outputs the internal fix path.

No additional fix would be needed.

**Comment by fsteeg** [comment]
Maybe this could be integrated into the `StreamFlattener` (flux command `flatten`)?

Functional review: @TobiasNx ; Code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
This came up again at KIM 2022. We need a way to inspect the paths that are entering and addressable in FIX.

**Comment by TobiasNx** [comment]
That looks good to me :)
