### ISSUE TITLE
Add `delete:`-Attribute to lookup and change the default filter-modus to an optional configuration

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#149]
In contrast to Catmandu lookup in metafacture fix is by default a filter.

Catmandu in contrast has the attribute `delete:`:

`lookup(color2,”lookup.csv”,delete:1)`

**Comment by blackwinter** [comment]
See [Catmandu::Fix::lookup test](https://github.com/hbz/Catmandu/blob/dev/t/Catmandu-Fix-lookup.t#L18-L22).

**Comment by TobiasNx** [comment]
@fsteeg can this be closed?

**Comment by blackwinter** [comment]
AFAICS, should have been closed by #170 (e9dd4ab).

**Comment by blackwinter** [comment]
Pending integration test:

- [lookupInSubfieldInArrayOfObjects_complex_2_withNotMatchingValue](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/lookup/fromJson/toJson/lookupInSubfieldInArrayOfObjects_complex_2_withNotMatchingValue)
