### ISSUE TITLE
Add `in`-conditional from Catmandu

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#151]
`in(JSONPath1,JSONPath2)`

Execute the fix(es) when all values in
the JSONPath1 can be found in
JSONPath2. 

E.g.
`x: 1`
`nums: [3,2,1]`

```
if in(x,nums)
  add_field(test,ok)
end
```

In my use case i want to compare if a value is part of a hash/object.

**Comment by blackwinter** [comment]
Duplicate of #234 (resolved by #235).
