### ISSUE TITLE
Change `substring()` Fix function to be compatible with Catmandu.

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#153]
Introduced in f328a13 with Metamorph semantics:

|Aspect|Metamorph|Catmandu|
|------|---------|--------|
|Second parameter|End index (exclusive)|Length of the substring|
|Substring beyond the end of the string|[Returns `null`](https://github.com/metafacture/metafacture-core/blob/89793c7c68999118dc625a18082e8c1f1ed5c1ca/metamorph/src/main/java/org/metafacture/metamorph/functions/Substring.java#L42) (i.e. [omits the value](https://github.com/metafacture/metafacture-core/blob/89793c7c68999118dc625a18082e8c1f1ed5c1ca/metamorph-api/src/main/java/org/metafacture/metamorph/api/helpers/AbstractSimpleStatelessFunction.java#L38))|Returns the string (i.e. ["cancels"](https://github.com/hbz/Catmandu/blob/bb54964bb2afe6a4ad46ceeafb5b77a3023f28cb/lib/Catmandu/Fix/substring.pm#L44) the [update](https://github.com/hbz/Catmandu/blob/bb54964bb2afe6a4ad46ceeafb5b77a3023f28cb/lib/Catmandu/Emit.pm#L123))|

Out of scope: [Substring replacement](https://github.com/hbz/Catmandu/blob/bb54964bb2afe6a4ad46ceeafb5b77a3023f28cb/lib/Catmandu/Fix/substring.pm#L53).

Cf. [Catmandu::Fix::substring tests](https://github.com/hbz/Catmandu/blob/bb54964bb2afe6a4ad46ceeafb5b77a3023f28cb/t/Catmandu-Fix-substring.t).

Functional review: @TobiasNx 
Code review: @fsteeg

**Comment by TobiasNx** [comment]
Just a quick question, index in Fix starts with 1 instead of 0, right?

**Comment by TobiasNx** [comment]
Nevermind, with substring it does with `0` i was just confused.

**Comment by blackwinter** [comment]
> Just a quick question, index in Fix starts with 1 instead of 0, right?

In Metafacture Fix yes (inherited from Metamorph), in Catmandu Fix no.

**Comment by TobiasNx** [comment]
okay, then I will push an integration test that does not seem to add up.

**Comment by TobiasNx** [comment]
See here: https://github.com/metafacture/metafacture-fix/commit/cba0bdad2bc48931308026155a00e5906fa5a664

**Comment by blackwinter** [comment]
Now I'm confused. I thought you realized that substring offsets started with 0. `"tacocat".substring(1, 4)` is `acoc`, not `taco`. See also the [unit tests](https://github.com/metafacture/metafacture-fix/pull/154/files#diff-bb6266bd9a7da63237fec55eb21906fe98b74a978fe6816b01421209660b51b7).

**Comment by TobiasNx** [comment]
> Now I'm confused. I thought you realized that substring offsets started with 0. `"tacocat".substring(1, 4)` is `acoc`, not `taco`. See also the [unit tests](https://github.com/metafacture/metafacture-fix/pull/154/files#diff-bb6266bd9a7da63237fec55eb21906fe98b74a978fe6816b01421209660b51b7).

Now we are all confused... :D Let me have a nother look.

**Comment by blackwinter** [comment]
I was referring to _array_ indices in my answer above. Didn't take the context into account, though, sorry.

**Comment by TobiasNx** [comment]
> > Just a quick question, [array] index in Fix starts with 1 instead of 0, right?
> 
> In Metafacture Fix yes (inherited from Metamorph), in Catmandu Fix no.

My confusion started here. I thought the same and that this is also true for `substring` as part of metafix.

**Comment by TobiasNx** [comment]
Then this is seems good to go. I will fix the test.

**Comment by TobiasNx** [comment]
+1
