### ISSUE TITLE
Evaluate Xtext language server with Monaco widget

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#17]
To evaluate using an Xtext-generated language server for Fix (and later Flux) in a web playground (and later IDE/editor):

- [x] Set up an Xtext project that generates a language server +  Connect a Monaco code editor widget to the language server: (https://github.com/nmaoez/composer-language-server)
- [x] Use the existing Fix grammar in the language server project: [Grammar file](https://github.com/metafacture/metafacture-fix/blob/master/org.metafacture.fix/src/main/java/org/metafacture/fix/Fix.xtext)
- [x] Load [fix file](https://gitlab.com/oersi/oersi-etl/-/raw/develop/data/production/edu-sharing.fix) from OERSI ETL as example fix file -> changed to [fix file](https://github.com/metafacture/metafacture-fix#editor) because of problems with first one
- [ ] Deploy server and client on one of our servers for internal review

**Comment by katauber** [comment]
Pushed current status to https://github.com/katauber/composer-language-server.

**Comment by fsteeg** [comment]
Thank you @katauber. I ran it on my machine and saw it working. But I keep getting errors like `java.lang.IllegalStateException: This language server has already been initialized` after reload etc. Also in the unmodified master of the sample project. You also mentioned it does not work with multiple tabs connecting to the server. I took a short look at the server code and there is quite a lot of implementation of central network communication in that sample project. Following this route, we'd probably be working a lot on building a robust server setup.

I kind of expected something different going into this whole thing: a full working server implementation generated by Xtext, which the client just has to talk to. While there is a working server generated by Xtext, it is not an out-of-the-box solution for our use case. Maybe it is much simpler when building a VS Code extension which talks to the Xtext language server via standard IO or something (we will try that in #20). But the use case we need for a metafacture-playground (#19) – connecting a code widget with an Xtext language server – seems to be rather bleeding edge. The other thing we learned here is that syntax coloring so far is not even part of the LSP, but defined on the client side in the Monaco editor config.

So given these two things, maybe it makes sense to actually keep out the LSP part at first for #19. Instead, we optimize the Monaco client side config for Fix to get nice syntax coloring. When we integrate running the Fix, we also get error messages, which we can display in the UI (#3). At a later point, we could then connect the whole thing to a language server – providing even better language integration on top, instead of using it as a starting point. I think this would allow us to focus on building a useful playground first. What do you think, @katauber, @acka47?

**Comment by acka47** [comment]
As discussed offline, we will first work on the extension for VS Code/vscodium (#20) as it is useful for adding sources to OERSI.
