### ISSUE TITLE
Set up metafacture-flux Xtext project with language server

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#21]
Using existing Xtext grammar from [metafacture-ide](https://github.com/culturegraph/metafacture-ide/tree/master/bundles/org.culturegraph.mf.ide/src/org/culturegraph/mf/ide).

Setup like for Fix: https://github.com/metafacture/metafacture-fix/issues/17 / https://github.com/metafacture/metafacture-fix/issues/18.

**Comment by katauber** [comment]
As discussed offline: Create an new Xtext project and copy [Flux grammar file](https://github.com/culturegraph/metafacture-ide/blob/master/bundles/org.culturegraph.mf.ide/src/org/culturegraph/mf/ide/Flux.xtext). Create a vs code extension for flux similar to #20

**Comment by fsteeg** [comment]
I've set up a repo for this at https://github.com/metafacture/metafacture-flux

**Comment by dr0i** [comment]
Not sure if this is a good name, as a Flux (as java programm, as shell script) already exists?

**Comment by fsteeg** [comment]
@TobiasNx: assigning you for functional review, see setup at https://github.com/metafacture/metafacture-flux. For problems and improvements, we should open new issues over there.

**Comment by TobiasNx** [comment]
Extension is running. Syntax highlighting, auto-completion and error-underlines seem to work.
Autocompletion is not working but that would be for a new ticket:
![2020-11-27_09-42](https://user-images.githubusercontent.com/61879957/100429293-6a808500-3095-11eb-8cf7-898a4a45f1fa.png)

**Comment by katauber** [comment]
@TobiasNx  Autocompletion does work but only for what is defined in the grammar file, not functions etc. 
It's the same in the fix extension ('do', 'if' etc work, 'map', 'add_field' does not work).

But you are right, that there should be a ticket with autocompletion for functions, collectors and so on.

**Comment by katauber** [comment]
Created #30 to improve autocompletion in flux extension. Closing.
