### ISSUE TITLE
Add `isbn`-function as in morph

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#231]
Morph has a specific [morph function for validating and transforming ISBNs](https://github.com/metafacture/metafacture-core/blob/master/metamorph/src/main/java/org/metafacture/metamorph/functions/ISBN.java).

This is used in the ALMA Transformation of lobid. We need a similar function in FIX.

**Comment by blackwinter** [comment]
Functional review: @TobiasNx
Code review: @fsteeg

**Comment by TobiasNx** [comment]
+1 great thanks
