### ISSUE TITLE
Support Catmandu `in`-conditional

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#234]
https://librecat.org/Catmandu/#conditionals

The `in` conditional compares a value of a source field with a target field.
If they have identical values then the condition is true. 

> `in(path1,path2)`
> 
> True, when the values of the first path1 are contained in the values at the second path2. False otherwise.
> 
> For instance to check if two paths contain the same values type:
> 
> ```
> if in(my.title,your.title)
>   set_field(same,1)
> end
> ```
> 
> To check if a value in one path is contained in a list of an other path type:
> 
> ```
> if in(my.author,your.authors.*)
>    set_field(known_author,1)
> end
> ```

This helps to avoid duplicate values or object when transforming metadata. I would need this for the ALMA-FIX.

**Comment by blackwinter** [comment]
Functional review: @TobiasNx
Code review: @fsteeg

**Comment by TobiasNx** [comment]
+1
