### ISSUE TITLE
Editor reports errors for production Fix

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#24]
Our production Fix from oersi-etl (https://gitlab.com/oersi/oersi-etl/-/blob/develop/data/production/edu-sharing.fix) results in errors when used in an Xtext-generated editor (see https://github.com/metafacture/metafacture-fix#visual-studio-code-extension). There seems to be some inconsistency between what can be executed and what is valid according to the grammar.

**Comment by fsteeg** [comment]
The problem here is that oersi-etl uses metafacture-fix's `oersi` branch, which contains changes to the Xtext grammer. So the fix file from oersi-etl is not valid with metafacture-fix master. (This shows that we should get https://github.com/metafacture/metafacture-fix/pull/16 merged soon. As metafacture-fix is a work in progress anyway, main development can happen in master.) For now I've merged @katauber's work from https://github.com/metafacture/metafacture-fix/issues/20 into the `oersi` branch. This should make it possible for @TobiasNx and @acka47 to test setting up the extension with these instructions: 

(the anchor link seems to be broken for that section, it's at the end of the README):
https://github.com/metafacture/metafacture-fix/tree/oersi#visual-studio-code-extension

And test it using the content of the fix file from oersi-etl:

https://gitlab.com/oersi/oersi-etl/-/blob/develop/data/production/edu-sharing.fix

You should see no errors in code/codium. Try removing some closing `)` and `'` to see errors.

**Comment by blackwinter** [comment]
Can't oersi-etl just declare a source dependency on the metafacture-fix `oersi` branch, just like we did here with metafacture-core? (#15)

**Comment by fsteeg** [comment]
> Can't oersi-etl just declare a source dependency on the metafacture-fix oersi branch, just like we did here with metafacture-core? (#15)

You mean to avoid having a build script that checks them out? Yes, it would in general be a nicer setup. I've had some issues with the source dependencies and the Eclipse project import though, which is why the branches differ at that point for now. I'll look into that (e.g. update Gradle support in my Eclipse) when trying to get  https://github.com/metafacture/metafacture-fix/pull/16 ready to be merged.

**Comment by TobiasNx** [comment]
> The problem here is that oersi-etl uses metafacture-fix's `oersi` branch, which contains changes to the Xtext grammer. So the fix file from oersi-etl is not valid with metafacture-fix master. (This shows that we should get #16 merged soon. As metafacture-fix is a work in progress anyway, main development can happen in master.) For now I've merged @katauber's work from #20 into the `oersi` branch. This should make it possible for @TobiasNx and @acka47 to test setting up the extension with these instructions:
> 

> (the anchor link seems to be broken for that section, it's at the end of the README):
> https://github.com/metafacture/metafacture-fix/tree/oersi#visual-studio-code-extension
> 
> And test it using the content of the fix file from oersi-etl:
> 
> https://gitlab.com/oersi/oersi-etl/-/blob/develop/data/production/edu-sharing.fix
> 
> You should see no errors in code/codium. Try removing some closing `)` and `'` to see errors.

@fsteeg I have tested the extension yesterday a little bit. But i have run the extension via a clone of the metafacture repo. If I want to run it via the  `oersi` branch do i need to delete the two metafacture repos created by `install_snapshots.sh` (as described here https://gitlab.com/oersi/oersi-etl/-/issues/27#note_445450829)?

**Comment by TobiasNx** [comment]
The extension in branch `oersi` runs without errors. Looks good.

**Comment by blackwinter** [comment]
That's what I meant, yes. Don't know about Eclipse, though...
