### ISSUE TITLE
Installation of VS Code extension

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-fix#25]
VS Code extensions should be easy to install (without cloning a repository).
Extensions can be published in the [Visual Studio Marektplace](https://marketplace.visualstudio.com/vscode) and/or in [Open VSX Registry](https://open-vsx.org/). Furthermore an Extension can be packaged in a .vsix-file and installed manually.

**Comment by fsteeg** [comment]
Following up on our offline discussion earlier about GitHub pages:

https://pages.github.com/

I've set up  a pages repo on the Metafacture organization level:

https://github.com/metafacture/metafacture.github.io

If you add e.g. `fix.vsix` and `flux.vsix` in the root there, they should be available under e.g.

https://metafacture.github.io/fix.vsix

**Comment by acka47** [comment]
I think we should set up a reverse proxy and serve this via metafacture.org (like we do it with blog.lobid.org).

**Comment by fsteeg** [comment]
Right, the existing https://metafacture.org proxy should go to https://metafacture.github.io, and index.html should for now redirect to metafacture-documentation. The extensions would then be available under e.g. https://metafacture.org/fix.vsix.

In any case, the actual files will be at the root of https://github.com/metafacture/metafacture.github.io.

**Comment by katauber** [comment]
The vsix-extension-files can be downloaded under https://metafacture.github.io/vsc/fix-0.0.1.vsix and https://metafacture.github.io/vsc/flux-0.0.1.vsix. To install click the 'Extension' symbol in VS Code and then 'Install from VSIX...' in the menu bar. In VS Codium it should be similar.

**Comment by acka47** [comment]
> The extensions would then be available under e.g. https://metafacture.org/fix.vsix.

I am not sure about this. We expect the Metafacture site to grow in the future so we might think about adjusting the path a bit, e.g. `https://metafacture.org/extensions/fix.vsix.`

**Comment by TobiasNx** [comment]
> The vsix-extension-files can be downloaded under https://metafacture.github.io/vsc/fix-0.0.1.vsix and https://metafacture.github.io/vsc/flux-0.0.1.vsix. To install click the 'Extension' symbol in VS Code and then 'Install from VSIX...' in the menu bar. In VS Codium it should be similar.

Installation works but there seems some problem with the Xtext-Server:

[Error - 09:30:36] Starting client failed
Launching server using command /home/user/.vscode/extensions/metafacture.flux-0.0.1/xtext-server/bin/xtext-server failed.

**Comment by fsteeg** [comment]
> Installation works but there seems some problem with the Xtext-Server for the FLUX-extension

Hm, here (codium 1.51.1) both seem to work fine.

**Comment by fsteeg** [comment]
> Hm, here (codium 1.51.1) both seem to work fine.

Oh, no, I take that back. Both editors look good, but don't actually show errors when I remove a `)` etc. It seems both do not connect to their language server? In the Output tab, I get the same error as @TobiasNx 

```
[Error - 9:05:18 AM] Starting client failed
Launching server using command /home/fsteeg/.vscode-oss/extensions/metafacture.fix-0.0.1/xtext-server/bin/xtext-server failed.
```

**Comment by katauber** [comment]
Hm ok, I will check that and give feedback as soon as possible! At the moment I can't reproduce the problem.

**Comment by fsteeg** [comment]
Maybe some issue with access rights on Linux? If I try to run the path from the error message I get:

`bash: /home/fsteeg/.vscode-oss/extensions/metafacture.fix-0.0.1/xtext-server/bin/xtext-server: Permission denied`

It seems there are no execution rights set on the file:

`ls -alh /home/fsteeg/.vscode-oss/extensions/metafacture.fix-0.0.1/xtext-server/bin/xtext-server`
`-rw-r--r-- 1 fsteeg fsteeg 6,9K Nov 30 08:56 /home/fsteeg/.vscode-oss/extensions/metafacture.fix-0.0.1/xtext-server/bin/xtext-server`

**Comment by acka47** [comment]
For the report:

- installation worked fine here
- synatx highlighting looks good
- I also get the error message from above

**Comment by acka47** [comment]
I just took another look at the Stardog VSC repo at https://github.com/stardog-union/stardog-vsc and noticed that there is no `.vsix` file in there. Apparently, there is another way of publishing the extensions...

**Comment by katauber** [comment]
@fsteeg to create an vsix-file:
- install vsce
- execute './gradlew installServer'
- in org.metafacture.fix.vsc execute 'npm install' and 'vsce package'

**Comment by katauber** [comment]
> I am not sure about this. We expect the Metafacture site to grow in the future so we might think about adjusting the path a bit, e.g. `https://metafacture.org/extensions/fix.vsix.`

As discussed offline I renamed the directory 'vsc' to 'extensions'

**Comment by fsteeg** [comment]
Additionally assigning @dr0i for proxy setup, see https://github.com/metafacture/metafacture-fix/issues/25#issuecomment-734356934, as discussed in standup.

**Comment by dr0i** [comment]
@fsteeg not sure why you assigned me resp. what I have to do besides https://github.com/metafacture/metafacture.github.io/pull/1 where I assigned you as reviewer.

**Comment by fsteeg** [comment]
> to create an vsix-file [...] in org.metafacture.fix.vsc execute 'npm install' and 'vsce package'

Great, I was able to build and install vsix files for fix and flux, both with syntax coloring and syntax checking via language server in my codium. I installed `vsce` with  `npm install -g vsce`. To have it support both the latest fix files from the oersi project and the latest syntax coloring tweaks, I merged `26-extension-syntax-highlighting` (see https://github.com/metafacture/metafacture-fix/pull/29) into my local `oersi` before building.

**Comment by fsteeg** [comment]
> @fsteeg not sure why you assigned me resp. what I have to do besides https://github.com/metafacture/metafacture.github.io/pull/1

No, right, that's it, I had not seen that yet.

**Comment by dr0i** [comment]
Done, see https://metafacture.org/ and the redirecting via `index.html` to documentation and visit https://metafacture.org/extensions/fix-0.0.1.vsix to download the extension.

**Comment by katauber** [comment]
@acka47 @TobiasNx Please install again the vsix files under https://metafacture.org/extensions/fix-0.0.1.vsix and https://metafacture.org/extensions/flux-0.0.1.vsix and try out if they are working now.

**Comment by acka47** [comment]
Works like a charm. Thanks!

**Comment by TobiasNx** [comment]
+1

**Comment by katauber** [comment]
To publish the extension(s) of fix and flux on https://open-vsx.org/ and https://marketplace.visualstudio.com/vscode the information in package.json should be like in [package.json, branch: 25-extension-installation](https://github.com/metafacture/metafacture-fix/blob/25-extension-installation/org.metafacture.fix.vsc/package.json)
But for the fix extension it would be nice, if the extension contains the better syntax highlighting like in master. Because branch [25-extension-installation](https://github.com/metafacture/metafacture-fix/tree/25-extension-installation) is based on branch [oersi](https://github.com/metafacture/metafacture-fix/tree/oersi) the better syntax highlighting is not included.
Because of problems when creating the vsix file with windows I can't create the vsix file by myself. @fsteeg could you please create the vsix file for fix with all necessary content and deploy it again, so I can publish it to the market places.

**Comment by fsteeg** [comment]
> could you please create the vsix file for fix with all necessary content and deploy it again

OK, here is what I did (being on branch `oersi` in metafacture-fix):

```bash
git merge origin/26-extension-syntax-highlighting
git merge origin/25-extension-installation
./gradlew clean installServer
cd org.metafacture.fix.vsc/
npm install
vsce package
cp fix-0.0.1.vsix ../../metafacture.github.io/extensions/
```

And then I added, committed, and pushed from `metafacture.github.io`.

**Comment by katauber** [comment]
@fsteeg Could you please create a new vsix file for the flux project with [this branch](https://github.com/metafacture/metafacture-flux/tree/25-extension-installation), too?

**Comment by katauber** [comment]
Fix extension ist now available in [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=metafacture.fix) and [Open VSX Registry](https://open-vsx.org/extension/metafacture/fix).
I think it would be nice if we add a picture and a README for both extensions. Should this be part of this ticket @fsteeg?

**Comment by fsteeg** [comment]
> @fsteeg Could you please create a new vsix file for the flux project with this branch, too?

Pushed https://github.com/metafacture/metafacture.github.io/commit/3e69e3b30e9d44d3e742329a3b69b22db1b3c85e

> a picture and a README for both extensions. Should this be part of this ticket @fsteeg?

Maybe that makes sense to do after https://github.com/metafacture/metafacture.github.io/issues/2, based on the content created there?

**Comment by katauber** [comment]
> Pushed [metafacture/metafacture.github.io@3e69e3b](https://github.com/metafacture/metafacture.github.io/commit/3e69e3b30e9d44d3e742329a3b69b22db1b3c85e)
Thank you! Flux extension is now also available in both marketplaces.

> Maybe that makes sense to do after [metafacture/metafacture.github.io#2](https://github.com/metafacture/metafacture.github.io/issues/2), based on the content created there?
Ok, then I will assign the two merge pull requests now.

**Comment by fsteeg** [comment]
Closing, related pull requests are merged. See:

https://github.com/metafacture/metafacture-fix/tree/oersi#extension
https://github.com/metafacture/metafacture-flux#metafacture-flux
