### ISSUE TITLE
Throw FixExecutionException instead of FixProcessException when Fix expression errors

### ISSUE THREAD

**Issue by dr0i** [metafacture/metafacture-fix#251]
In some circumstances, when Fix expression errors, it's an `IllegalArgumentException` and thus not handled as expected when setting `Metafix.Strictness.EXPRESSION` because that would presupposed a `FixProcessException`.

Going to set up a test.

**Comment by dr0i** [comment]
Test set up, see #252. Enable the integration test by removing `metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpper/todo.txt`.

**Comment by blackwinter** [comment]
Functional review: @dr0i 
Code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
This was originally spotted in context of https://github.com/hbz/lobid-resources/issues/1372

**Comment by dr0i** [comment]
+1 for functional review: ETL goes on, even if Fix errors occur. Thx!

**Comment by blackwinter** [comment]
This issue only deals with ignoring any underlying bugs; we'd need a new issue for the one you encountered.

**Comment by dr0i** [comment]
> This issue only deals with ignoring any underlying bugs; we'd need a new issue for the one you encountered.

not sure about this: almost all  Exceptions are results of faulty data. You don't mean to open issues because of faulty data?
We got those Exceptions:

> java.lang.IllegalArgumentException: Can't find: $number in: null
java.lang.IllegalStateException: Expected String, got Array
java.lang.IllegalStateException: No match available
java.lang.NullPointerException
java.util.ConcurrentModificationException

whereas , admittiingly, at least the `ConcurrentModificationException` seems to be a nasty ("real") bug (which only occured once within several millions of documents).

**Comment by blackwinter** [comment]
The error from your integration test was `java.lang.IllegalArgumentException: Can't find: 2 in: null`. That _looks_ like a bug. `strictnessHandlesProcessExceptions` was certainly not meant as a permanent setting.

**Comment by dr0i** [comment]
See https://github.com/hbz/lobid-resources/issues/1409 for more analytics.
@TobiasNx identified `Reason: Seems to be an array.` whereas a `String` was expected.

**Comment by blackwinter** [comment]
Exactly, the error should be `java.lang.IllegalStateException: Expected String, got Array`. Besides, `replace_all()` should _technically_ be able to operate on arrays, it looks like. So something's not right.

**Comment by blackwinter** [comment]
> Besides, `replace_all()` should _technically_ be able to operate on arrays, it looks like.

I retract this part. I found the place where strings are enforced. So this leaves us with the fact that this check is somehow not triggered.

**Comment by blackwinter** [comment]
Pending integration test:

- [replace_toUpper](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/method/fromXml/toJson/replace_toUpper)
