### ISSUE TITLE
Fix-Extension: Syntax Highlighting 

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#26]
Different requirements for the syntax higlighting of the Fix-extension:

- [x] comment recognition

- [x] different colors at the moment only purple is used

- [x]  `do` and its closing `end` should have the same color

**Comment by katauber** [comment]
@TobiasNx To install, see: https://github.com/metafacture/metafacture-fix#visual-studio-code-extension
If everything works as expected, please assign the corresponding pull request #29 to @fsteeg

**Comment by TobiasNx** [comment]
Looks good to me. Great!

**Comment by katauber** [comment]
Extension availaible under https://metafacture.github.io/vsc/fix-0.0.1.vsix
