### ISSUE TITLE
Add options for multi column lookup to `put_filemap()`

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#265]
@blackwinter Introduced multi column lookup to metafacture morph. to use this in fix we need some additional options with `put_filemap()`

https://github.com/metafacture/metafacture-core/pull/471

**Comment by blackwinter** [comment]
The feature has been merged, now we have to wait for a (pre-)release before we can continue here.

**Comment by dr0i** [comment]
Do I understand this correctly - you need a pre release of metafacture-core to enable this in Metafix? Would [a sonatype snaphsot](https://github.com/metafacture/metafacture-core/issues/411#issuecomment-945838656) be enough?

**Comment by blackwinter** [comment]
It depends on how urgent this is for @TobiasNx. IMO, we should try not to depend on snapshot releases.

**Comment by TobiasNx** [comment]
We need this for : https://github.com/hbz/lobid-resources/issues/1473 which blocks https://github.com/hbz/lobid-resources/issues/1471

**Comment by dr0i** [comment]
@blackwinter: what shall we do ? As I would not want to go through the hassle of a maven publication:
are you ok with working on a feature branch (which lobid-resources could use then) or would you rather want to consume a github package (which we could use a kind of "pre release" as @fsteeg suggested)?

**Comment by blackwinter** [comment]
A GitHub package would be sufficient.

**Comment by blackwinter** [comment]
> are you ok with working on a feature branch

We need a published artifact of metafacture-core to consume in metafacture-fix. A feature branch wouldn't help.

**Comment by blackwinter** [comment]
> A GitHub package would be sufficient.

Now that the [packages are up](https://github.com/metafacture/metafacture-core/packages/676411), maybe I spoke too soon. We can't (rather, shouldn't) depend on unstable versions.

But as you said that a feature branch was acceptable for lobid-resources, you can work off of the WIP PR #266, right?

**Comment by dr0i** [comment]
Yes, working with a fetaure branch is ok for me.

**Comment by dr0i** [comment]
@TobiasNx can you do the functional review using the branch `265-filemapOptions`?

**Comment by TobiasNx** [comment]
I try to set an integration test for this. But it seems not to work yet. @blackwinter could you have a look?

**Comment by blackwinter** [comment]
Look where? What's not working?

**Comment by TobiasNx** [comment]
@blackwinter : I didn't push. Should be pushed now. Sorry.

**Comment by TobiasNx** [comment]
Thanks
