### ISSUE TITLE
Support combining corresponding arrays

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#267]
Use case from oersi-etl, see https://gitlab.com/oersi/oersi-etl/-/issues/221.

Input data:

```json
"ccm:university": [
  "https://ror.org/0304hq317",
  "https://ror.org/014nnvj65"
],
"ccm:university_DISPLAYNAME": [
  "Gottfried Wilhelm Leibniz Universität Hannover",
  "Technische Hochschule Köln"
]
```
Desired output data:

```json
"sourceOrga": [
  {"name": "Gottfried Wilhelm Leibniz Universität Hannover", "id": "https://ror.org/0304hq317"},
  {"name": "Technische Hochschule Köln", "id": "https://ror.org/014nnvj65"}
]
```

See https://gitlab.com/oersi/oersi-etl/-/issues/221 for a discussion of different approaches.

**Comment by blackwinter** [comment]
This would be my - tentative, untested - take on `parallelList` (or whatever name we come up with):

```diff
diff --git metafix/src/main/java/org/metafacture/metafix/FixBind.java metafix/src/main/java/org/metafacture/metafix/FixBind.java
index c942d91..cccda09 100644
--- metafix/src/main/java/org/metafacture/metafix/FixBind.java
+++ metafix/src/main/java/org/metafacture/metafix/FixBind.java
@@ -26,6 +26,32 @@ import java.util.Set;
 
 public enum FixBind implements FixContext {
 
+    parallelList {
+        @Override
+        public void execute(final Metafix metafix, final Record record, final List<String> params, final Map<String, String> options, final RecordTransformer recordTransformer) {
+            final Map<String, Value.Array> lists = new HashMap<>();
+            options.forEach((k, v) -> Value.asList(record.get(v), a -> lists.put(k, a)));
+
+            final int size = lists.values().stream().mapToInt(a -> a.size()).max().orElse(0);
+            for (int i = 0; i < size; ++i) {
+                final int index = i;
+
+                lists.forEach((k, v) -> {
+                    if (index < v.size()) {
+                        record.put(k, v.get(index));
+                    }
+                    else {
+                        record.remove(k);
+                    }
+                });
+
+                recordTransformer.transform(record);
+            }
+
+            lists.keySet().forEach(record::remove);
+        }
+    },
+
     list {
```

Let me know if I should pursue it...

**Comment by fsteeg** [comment]
> Let me know if I should pursue it...

Yes, thanks, that would be great!

> `parallelList` (or whatever name we come up with) [...] I'm fine with trying to find a better name that also works for a single list. (from the oers-etl discussion)

How about focusing on the the key semantics, with something like `list_as`:

```perl
set_array("sourceOrga[]")
do list_as(orgId: "ccm:university[]", orgName: "ccm:university_DISPLAYNAME[]")
  copy_field(orgId, "sourceOrga[].$append.id")
  copy_field(orgName, "sourceOrga[].$last.name")
end
```

I think this reads well (_list as orgId_...) and would also work for single lists.

**Comment by blackwinter** [comment]
> Yes, thanks, that would be great!

Basic PR is up: #268. More tests and documentation still to do.

> How about focusing on the the key semantics, with something like `list_as`:

Sure, fine with me.

**Comment by TobiasNx** [comment]
Functionally this work +1.

Conceptually: At first sight I dislike the `bind` name and also the deviation from the `list`-bind.
Wouldn't it make more seens to introduce `list`-Bind that allows for iterating over multiple lists at once that would allow to do this with arrays of strings as well as arrays of objects? Is the use case for array of objects needed at all? I am not sure perhaps not.

e.g.: `do lists`
with array of strings:

```
set_array("sourceOrga[]")
do lists(list1: "ccm:university[]", "var1":"$i",  list2: "ccm:university_DISPLAYNAME[], "var2": "$j")
  copy_field("$i", "sourceOrga[].$append.id")
  copy_field("$j", "sourceOrga[].$last.name")
end
```


```
set_array("contribution[]")
do lists(list1: "creator[]", "var1":"$i",  list2: "sourceOrganization[], "var2": "$j")
  copy_field("$i.name", "contribution.$append.name")
  copy_field("$j.name", "contribution[].$last.affiliation")
end
```

But lets move on. If the use-case for array of objects appears we could still re-do this.

**Comment by blackwinter** [comment]
I'm not sure I understand, both cases are supported.

As for the name, I'll let you two decide ;)

**Comment by TobiasNx** [comment]
The options in `list`-bind are: `path` and `var`. 
The options in`list-as` are: `[varname1]`, `[varname2]` etc. and are called without `"`:
```
set_array("sourceOrga[]")
do list_as(orgId: "ccm:university[]", orgName: "ccm:university_DISPLAYNAME[]")
  copy_field(orgId, "sourceOrga[].$append.id")
  copy_field(orgName, "sourceOrga[].$last.name")
end
```

**Comment by blackwinter** [comment]
`list_as` uses key/value pairs (options), just like `list`. The only difference is that the keys aren't fixed.

Quotes are (sometimes) optional, there's nothing to it.
