### ISSUE TITLE
Fix-Extension: Add auto-close functionality (do ... end)

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#27]
When entering a function or a collector that starts with `do`, the editor should auto close with `end`. 
The `end` should emerge in the next line on the same level as the do.

e.g.;
```
do array('sourceOrganization')
 do entity('')
  add_field('type', 'Organization')
  do map('node.properties.ccm:university_DISPLAYNAME[].1', 'name')
    not_equals(string: '')
    not_equals(string: '- Alle -')
  end
 end
end
```

**Comment by katauber** [comment]
@TobiasNx and @acka47 please download the [new version of the fix extension](https://www.metafacture.org/extensions/fix.vsix) to install the new fix extension and to review the do-end-snippet.

**Comment by acka47** [comment]
It works. When I type "do" and hit enter, I get:

```
do collector(args)
  body
end
```

"collector" is then marked so that I can directly continue typing. However, I am not sure whether the other placeholders make things easier. I could imagine that at least omitting the "body" placeholder might be more user-friendly. However, I am not workig with fix on a regular basis, so that I thin @TobiasNx should decide on this.

**Comment by TobiasNx** [comment]
Yes it also works for me. I also just learned that when I hit TAB I can switch to the argument and the body to and can continue typing there too. I am fine with the body placeholder and the argument placeholder. But I am not that experienced with editors and usability conventions.

One additional function for that do ... end autoclose would be nice: 
I usually write the `do _collector_` e.g. `do map`or `do combine`. So it would be nice if the autoclose would work if hit ENTER oder TAB after typing `do _collector_`

**Comment by katauber** [comment]
> I usually write the `do _collector_` e.g. `do map`or `do combine`. So it would be nice if the autoclose would work if hit ENTER oder TAB after typing `do _collector_`
At first I tried to implement the feature like this, but there were problems with a correct indentation when the 'do'-bind itself was already indented. To implement a really 'intelligent' solution, the language server must become 'smarter', which should happen in next steps (the current solution is a client-side implementation).
