### ISSUE TITLE
`isbn`-Function in `list`-Bind does not work

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#272]
in:
```
{
"isbn13" : [ "1556199724" ]
}
```

fix:
```
do list(path:"isbn13[]","var":"$i")
    isbn("$i", to:"isbn13")
end
```

out:
```
{
  "isbn13" : [ "1556199724" ]
}
```

expected:
```

{
  "isbn13" : [ "9781556199721" ]
}
```

[Playground-Example](https://metafacture.org/playground/?flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=%0Ado+list%28path%3A%22isbn13%5B%5D%22%2C%22var%22%3A%22%24i%22%29%0A++++isbn%28%22%24i%22%2C+to%3A%22isbn13%22%29%0Aend%0A&data=%0A%7B%0A%22isbn13%22+%3A+%5B+%221556199724%22+%5D%0A%7D%0A%0A%7B%0A%22isbn13%22+%3A+%5B+%229027237018%22+%5D%0A%7D+%0A&active-editor=fix)

**Comment by blackwinter** [comment]
`isbn()` modifies the field `$i`, which you then have to place in the record with `copy_field()` (see [fixed example](https://metafacture.org/playground/?flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=do+list%28path%3A%22related%5B%5D%22%2C+%22var%22%3A%22%24i%22%29%0A++++set_array%28%22%24i.isbn13%5B%5D%22%29%0A++++do+list%28path%3A%22%24i.isbn10%5B%5D%22%2C%22var%22%3A%22%24k%22%29%0A++++++++isbn%28%22%24k%22%2C+to%3A%22isbn13%22%29%0A++++++++copy_field%28%22%24k%22%2C+%22%24i.isbn13%5B%5D.%24append%22%29%0A++++end%0Aend&data=%7B%0A%22related%22+%3A+%5B+%7B%0A++++%22isbn10%22+%3A+%5B+%221556199724%22%2C+%221556199724%22+%5D%0A++%7D%2C+%7B%0A++++%22isbn10%22+%3A+%5B+%229027237018%22%2C+%229027237018%22+%5D%0A++%7D+%5D%0A%7D&active-editor=fix)).
