### ISSUE TITLE
Add function to percent-encode strings

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#273]
Catmandu has:
```

# '3%A9' => 'café'
uri_decode(place)
# 'café' => '3%A9'
uri_encode(place)
```

MF Morph has `urlencode`(https://github.com/metafacture/metafacture-core/blob/master/metamorph/src/main/java/org/metafacture/metamorph/functions/URLEncode.java):

```
<data source="suchwert">
  <urlencode />
  <compose prefix="https://swissbib.ch/Search/Results?lookfor="/>
</data>
```

We need this for formatting/encoding ids in lobid:

```
"hasItem" : [ {
    "label" : "lobid Bestandsressource",
    "type" : [ "Item", "PhysicalObject" ],
    "callNumber" : "61 TYD 16(3)",
    "currentLocation" : "JUE / JUE_Frei",
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-A96#!",
      "isil" : "DE-A96",
      "label" : "lobid Organisation"
    },
    "id" : "http://lobid.org/items/990223521400206441:DE-A96:61 TYD 16(3)#!"
  }, {
    "label" : "lobid Bestandsressource",
    "type" : [ "Item", "PhysicalObject" ],
    "callNumber" : "61 TYD 16(3)",
    "currentLocation" : "JUE / JUE_Frei",
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-A96#!",
      "isil" : "DE-A96",
      "label" : "lobid Organisation"
    },
    "id" : "http://lobid.org/items/990223521400206441:DE-A96:61 TYD 16(3)#!"
  },
```

**Comment by TobiasNx** [comment]
Needed for: https://github.com/hbz/lobid-resources/issues/1521

**Comment by TobiasNx** [comment]
@dr0i / @blackwinter : can this be reused for the function: https://github.com/metafacture/metafacture-core/blob/master/metamorph/src/main/java/org/metafacture/metamorph/functions/URLEncode.java

**Comment by blackwinter** [comment]
Yes, Metamorph's `urlencode()` can be used for Catmandu's `uri_encode()`.

BTW: Your initial examples are incomplete, `'3%A9'` should be `'caf%C3%A9'`.

**Comment by TobiasNx** [comment]
> Yes, Metamorph's `urlencode()` can be used for Catmandu's `uri_encode()`.
> 
> BTW: Your initial examples are incomplete, `'3%A9'` should be `'caf%C3%A9'`.

@blackwinter:
I copied the example from here: https://github.com/LibreCat/Catmandu/wiki/Fixes-Cheat-Sheet.
You could provide a commit or should I do it.

**Comment by dr0i** [comment]
Resolved with https://github.com/metafacture/metafacture-fix/pull/314.
Closing.

**Comment by dr0i** [comment]
The former metamorph function defines more `safe chars` as  the new `PercentEscaper` defines per default. So these were also safe before:
> The special characters ".", "-", "*", and "_" remain the same. 
(https://docs.oracle.com/javase/1.5.0/docs/api/java/net/URLEncoder.html)

How should we go on?
1. adding these 4 characters as to safe chars as default 
2. introduce an option `safe_chars` to let users set them as they wish (see https://github.com/metafacture/metafacture-fix/pull/314#discussion_r1232295575)

Maybe both of them would be good? Because it seems that [2292f6c716cf2248907711f43f692de16280b713](https://github.com/metafacture/metafacture-core/commit/2292f6c716cf2248907711f43f692de16280b713) has breaked backwards compatibility.

**Comment by blackwinter** [comment]
My votes:

1. +0
2. +1

**Comment by fsteeg** [comment]
> Maybe both of them would be good?

This sounds good to me, if I understand it correctly:

Characters `.`, `-`, `*`, and `_` will not be escaped by default, and that was our original behavior, before the recent change. But we can set a `safe_chars` option to actually escape them.

But what would that look like exactly? We'd have to set something like `[a-zA-Z0-9]`, right? But does PercentEscaper support regexes here? So in that aspect, I'm not so sure making `safe_chars` a Fix option is actually useful.

Also, did we not implement the approach from https://github.com/metafacture/metafacture-fix/pull/285#issuecomment-1442047613? In particular:

> In the default used in `metamorph`, we use [SAFECHARS_URLENCODER](https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.util.escape.PercentEscaper#com_google_api_client_util_escape_PercentEscaper_SAFECHARS_URLENCODER), which "mimics the behavior of java.net.URLEncoder" (thus no break), and in `metafix` we use e.g. [SAFE_PLUS_RESERVED_CHARS_URLENCODER](https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.util.escape.PercentEscaper#com_google_api_client_util_escape_PercentEscaper_SAFE_PLUS_RESERVED_CHARS_URLENCODER) (to get what we need in lobid-resources and be consistent with `Catmandu::Fix::uri_encode`).

**Comment by dr0i** [comment]
> Characters ., -, *, and _ will not be escaped by default, and that was our original behavior, before the recent change.

no. Opposite. These _were_ safe before (and will be again as default, see metafacture/metafacture-core#507 )

> But we can set a safe_chars option to actually escape them.

`safe_chars ` will be configurable, yes, see metafacture/metafacture-core#507 

> But what would that look like exactly? We'd have to set something like [a-zA-Z0-9], right?

no. These are always safe as default, cannot be made unsafe.

Re [SAFECHARS_URLENCODER](https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.util.escape.PercentEscaper#com_google_api_client_util_escape_PercentEscaper_SAFECHARS_URLENCODER),: 
These static fields only exists in a guava version we don't use.  (I also the slight remberance on having trouble using different guava versions). The `safe_chars` of URLEncoder ae well known so they can be easily set, see metafacture/metafacture-core#507 .

**Comment by dr0i** [comment]
Closing as completed.
