### ISSUE TITLE
Add additional metafacture libraries to runner

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#275]
I wanted to use the triples functions with the runner, but this seems not to work since the lib is not included in the runner:

```
dependencies {
  implementation project(':metafix')

  implementation "org.metafacture:metafacture-biblio:${versions.metafacture}"
  implementation "org.metafacture:metafacture-json:${versions.metafacture}"
  implementation "org.metafacture:metafacture-runner:${versions.metafacture}"
  implementation "org.metafacture:metafacture-xml:${versions.metafacture}"

  implementation('org.antlr:antlr-runtime') {
    version { strictly versions.antlr }
  }
}
```

Would be nice to integrate more Metafacture libraries into the runner.

**Comment by fsteeg** [comment]
Added all metafacture modules to metafix-runner in https://github.com/metafacture/metafacture-fix/commit/711b787d4c5d5320bc75487e2208f200b10eab57.

In branch `275-runner`, create a distribution with `./gradlew distZip` for testing.

**Comment by TobiasNx** [comment]
I tested it with triples which were missing, seems to work, nice :)

**Comment by TobiasNx** [comment]
@fsteeg do you intend to release 0.4.1 to make this available?

**Comment by fsteeg** [comment]
> @fsteeg do you intend to release 0.4.1 to make this available?

I wasn't planning to do that, no, but we could.

**Comment by TobiasNx** [comment]
> > @fsteeg do you intend to release 0.4.1 to make this available?
> 
> I wasn't planning to do that, no, but we could.

I would allow to use all libraries with the cli right away and not have to wait for the next big release.
We could provide an easier "Getting started" and I could improve the tutorial
