### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#28]
Clean up, update and perhaps restructure the readme.md and add table of contents.

**Comment by fsteeg** [comment]
See: https://github.com/metafacture/metafacture-fix/blob/oersi/README.md

It's much shorter now, so maybe it's ok like this, without a TOC. Currently, everything needs to be set up anyways. When we have a way to set up the extension without building the language server etc we should probably set up separate user and developer documentations.

**Comment by katauber** [comment]
The site is much clearer now. I think a TOC would be nice but is not absolutely necessary.
Maybe it should be mentioned, that starting the extension in this way is for developing?

**Comment by TobiasNx** [comment]
> The site is much clearer now. I think a TOC would be nice but is not absolutely necessary.
> Maybe it should be mentioned, that starting the extension in this way is for developing?

I think @katauber is right, it is much clearer now. I also agree with her suggestion about a TOC.

**Comment by fsteeg** [comment]
Great, thanks for the feedback. Pushed minor tweak in https://github.com/metafacture/metafacture-fix/commit/0b53d785b7686940fe388f445fb87a2448430501. Closing.
