### ISSUE TITLE
Create variables from element values or names.

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#282]
At the moment you can only create variables from explicitly assigning values to variable names by `put_var` or `put_vars`.

I suggest a `to_var` function:

 `to_var("sourceElement","variableName",variableValue:"key/value")`

Perhaps the feature for element names is not needed.

**Comment by blackwinter** [comment]
> `variableValue:"key/value"`

I dont't understand this part. What would it do?

> Perhaps the feature for element names is not needed.

And this isn't clear to me, either. What is the "feature for element names"?

**Comment by TobiasNx** [comment]
> > `variableValue:"key/value"`
> 
> I don't understand this part. What would it do?

element:

`"a" : "b"`

1. value:
`to_var("a","variableName",variableValue:"value")`

Variable: `$[variableName]="b"`

2. key:
`to_var("a","variableName",variableValue:"key")`

Variable: `$[variableName]="a"`


> > Perhaps the feature for element names is not needed.
> 
> And this isn't clear to me, either. What is the "feature for element names"?

I was referring to 2 and therefore questioned if we need the option `variableValue:` at all.

**Comment by blackwinter** [comment]
I see, thanks for the clarification.

> I was referring to 2 and therefore questioned if we need the option `variableValue:` at all.

As this would be equivalent to `put_var('variableName', 'a')`, I don't think we should pursue it.

**Comment by blackwinter** [comment]
But we need to specify how `to_var()` should behave if the path (`sourceElement`) matches a non-string.

**Comment by blackwinter** [comment]
We've previously discussed a similar issue in [oersi/oersi-etl#221](https://gitlab.com/oersi/oersi-etl/-/issues/221#note_1162561399). The proposed "field value interpolation" would also be able to satisfy the [use case](https://github.com/hbz/lobid-resources/issues/1605#issuecomment-1386856215) here, thus obviating the need for a new function.

**Comment by TobiasNx** [comment]
> But we need to specify how `to_var()` should behave if the path (`sourceElement`) matches a non-string.

This should only work with string-elements, and should be overwritten if already exists.

I am not sure, but perhaps some of the code could be reused in https://github.com/metafacture/metafacture-core/issues/533
