### ISSUE TITLE
Release 0.4.0 on GitHub

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#286]
If there are no objections, I'd like to like to release the current master as 0.4.0 on GitHub:

- [x] Bump development version to 0.5.0-SNAPSHOT
- [x] Create 0.4.0 GitHub packages
- [x] Create 0.4.0 GitHub release with distribution download

**Comment by blackwinter** [comment]
:+1:, except maybe releasing Metafacture Core 5.4.1 first? So we don't depend on a pre-release.

**Comment by fsteeg** [comment]
Released metafacture-fix 0.4.0 based on metafacture-core 5.5.0: [package](https://github.com/metafacture/metafacture-fix/packages/1065549), [release](https://github.com/metafacture/metafacture-fix/releases/tag/0.4.0).

Tested build in OERSI: https://gitlab.com/oersi/oersi-etl/-/merge_requests/284
