### ISSUE TITLE
Update VSC Extension

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-fix#291]
Due to changes in Metafacture Fix the VSC Extension should be updated by using the latest Fix version and adapting the syntax highlighting.
[This](https://github.com/hbz/lobid-resources/tree/master/src/main/resources/alma/fix) can be used for functional review.
The pictures at https://metafacture.org/ide-extensions/index.html should be exchanged.

functional review: @TobiasNx 
code review: @fsteeg

**Comment by dr0i** [comment]
I have added this issue to the *Metafacture* Projects so that it appears at our metafacture board at https://github.com/orgs/metafacture/projects/3/views/4.

**Comment by TobiasNx** [comment]
Things I noticed and would be nice:

some words as `type` and `entity` withou `""` are highlighted in different style

`replace_all`, `add_field`, `timestamp`, `isbn`, `lookup`, `substring` are functions that differ from other function in style

Comments with `#`  are not styled as such.

**Comment by katauber** [comment]
I uploaded the vsix file to our `oi-austausch` directory. For installation see the [installation instructions](https://metafacture.org/ide-extensions/index.html)

**Comment by TobiasNx** [comment]
![grafik](https://user-images.githubusercontent.com/61879957/235660264-9e9894ee-2687-4a80-ac25-b029860b14fe.png)

Looks promising.

Two things I found option `"var"` in `do list`, is not highlighted as option, probably because of the `"`
`join_field` is not highlighted differently than other functions.

Perhaps binds (`list` etc. eveything with do in front of it) and conditionals (eveything with if/elif/unless in front of it) should be highlighted differently than function

**Comment by TobiasNx** [comment]
strange reaction to shebang:
![grafik](https://user-images.githubusercontent.com/61879957/235690398-ba5c528d-b52e-4055-bc18-edb156a7889d.png)

**Comment by katauber** [comment]
> Looks promising.
> 
> Two things I found option `"var"` in `do list`, is not highlighted as option, probably because of the `"` 

Options are not highlighted. I think it's because of your theme that e.g. path is blue. In my theme it's white (not highlighted).

> `join_field` is not highlighted differently than other functions.
> 

That was also not highlighted because of a typo.

> Perhaps binds (`list` etc. eveything with do in front of it) and conditionals (eveything with if/elif/unless in front of it) should be highlighted differently than function

There are four groups: Fix controls (like `do`, `if` etc), fix methods (like `inlcude`, `put_map` etc), fix conditionals (like `all_contain`, `any_contain` etc) and Fix binds (like `list`, `list_as` etc). To highlight them in different colors I have to mark them as different groups according to this [documentation](https://macromates.com/manual/en/language_grammars#naming-conventions). I am not really happy with this solution because I think that binds and methods should be both in the entity group and controls and conditionals also both in one group which would lead to having the same color.
But I can live with this solution.


> strange reaction to shebang: ![grafik](https://user-images.githubusercontent.com/61879957/235690398-ba5c528d-b52e-4055-bc18-edb156a7889d.png)

I cannot reproduce this behaviour. I will put the new extension again in `oi-austausch`. Please test if it still behaves like this.

**Comment by TobiasNx** [comment]
+1
