### ISSUE TITLE
Nested do list does not work wih creating arrays??

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#292]
In context of oersi we found tghe following

do list(path:"html.head.meta","var":"$i") does not work with element-mappins (id, name, description, dateCreated, license work, creator and inLanguage do not work and create empty arrays). the difference seems to be mappin into an array.

```
vacuum()
do list(path:"html.head.meta","var":"$i")

  /* Map some of the data we have to the oersi model: */
  # ---------------id --------
  copy_field("$i.DC_Identifier_URI", "id")

  # ---------------name --------
  copy_field("$i.citation_title", "name")


  # ---------------description --------
  copy_field("$i.DC_Description", "description")


  # ---------------dateCreated --------
  copy_field("$i.DC_Date_created", "dateCreated")
  
      # ---------------license --------
  if any_match("$i.DC_Rights","https://creativecommons.org/.*")
    copy_field("$i.DC_Rights", "license.id")
  end

  # ------ creator --- 
  set_array("creator[]")
  copy_field("$i.DC_Creator_PersonalName", "creator[].$append.name")
  add_field("creator[].*.type", "Person")


  # ------ inLanguage------
  set_array("inLanguage[]")
  copy_field("$i.DC_Language", "inLanguage[].$append")

end

retain("@context[]","id","image","name","creator[]","contributor[]","sourceOrganization[]", "license","description","datePublished","dateCreated","dateModified","inLanguage[]","type[]","learningResourceType[]","keywords[]","about[]", "encoding[]", "publisher[]", "isPartOf[]", "mainEntityOfPage[]","conditionsOfAccess","duration")
```

[See Playground](https://metafacture.org/playground/?flux=%22https%3A//langsci-press.org/catalog/book/16%22%0A%7C+open-http%0A%7C+as-records%0A%7C+match%28pattern%3D%22%28name%3D\%22DC%29\\.%28\\w%2A%3F%29\\.%28\\w%2A%3F%29%28\%22%29%22%2C+replacement%3D%22%241_%242_%243%244%22%29%0A%7C+match%28pattern%3D%22%28name%3D\%22DC%29\\.%28\\w%2A%3F%29%28\%22%29%22%2C+replacement%3D%22%241_%242%243%22%29%0A%7C+read-string%0A%7C+decode-html%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B%0A&fix=vacuum%28%29%0Ado+list%28path%3A%22html.head.meta%22%2C%22var%22%3A%22%24i%22%29%0A%0A++/%2A+Map+some+of+the+data+we+have+to+the+oersi+model%3A+%2A/%0A++%23+---------------id+--------%0A++copy_field%28%22%24i.DC_Identifier_URI%22%2C+%22id%22%29%0A%0A++%23+---------------name+--------%0A++copy_field%28%22%24i.citation_title%22%2C+%22name%22%29%0A%0A%0A++%23+---------------description+--------%0A++copy_field%28%22%24i.DC_Description%22%2C+%22description%22%29%0A%0A%0A++%23+---------------dateCreated+--------%0A++copy_field%28%22%24i.DC_Date_created%22%2C+%22dateCreated%22%29%0A%0A%23+---------------license+--------%0A++if+any_match%28%22%24i.DC_Rights%22%2C%22https%3A//creativecommons.org/.%2A%22%29%0A++++copy_field%28%22%24i.DC_Rights%22%2C+%22license.id%22%29%0A++end%0A%0A++%23+------+creator+---+%0A++set_array%28%22creator%5B%5D%22%29%0A++copy_field%28%22%24i.DC_Creator_PersonalName%22%2C+%22creator%5B%5D.%24append.name%22%29%0A++add_field%28%22creator%5B%5D.%2A.type%22%2C+%22Person%22%29%0A%0A%0A++%23+------+inLanguage------%0A++set_array%28%22inLanguage%5B%5D%22%29%0A++copy_field%28%22%24i.DC_Language%22%2C+%22inLanguage%5B%5D.%24append%22%29%0A%0Aend%0A%0Aretain%28%22@context%5B%5D%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22creator%5B%5D%22%2C%22contributor%5B%5D%22%2C%22sourceOrganization%5B%5D%22%2C+%22license%22%2C%22description%22%2C%22datePublished%22%2C%22dateCreated%22%2C%22dateModified%22%2C%22inLanguage%5B%5D%22%2C%22type%5B%5D%22%2C%22learningResourceType%5B%5D%22%2C%22keywords%5B%5D%22%2C%22about%5B%5D%22%2C+%22encoding%5B%5D%22%2C+%22publisher%5B%5D%22%2C+%22isPartOf%5B%5D%22%2C+%22mainEntityOfPage%5B%5D%22%2C%22conditionsOfAccess%22%2C%22duration%22%29%0A%0A&active-editor=fix)

when setting the do list path deeper it works: do list(path:"html.head.meta.DC_Creator_PersonalName","var":"$i")

```

do list(path:"html.head.meta.DC_Creator_PersonalName","var":"$i")
  # ------ creator --- 
  set_array("creator[]")
  copy_field("$i", "creator[].$append.name")
end
add_field("creator[].*.type", "Person")

do list(path:"html.head.meta.DC_Language","var":"$i")
  # ------ inLanguage------
  set_array("inLanguage[]")
  copy_field("$i", "inLanguage[].$append")
end

retain("@context[]","id","image","name","creator[]","contributor[]","sourceOrganization[]", "license","description","datePublished","dateCreated","dateModified","inLanguage[]","type[]","learningResourceType[]","keywords[]","about[]", "encoding[]", "publisher[]", "isPartOf[]", "mainEntityOfPage[]","conditionsOfAccess","duration")

```

it works,. [see playground](https://metafacture.org/playground/?flux=%22https%3A//langsci-press.org/catalog/book/16%22%0A%7C+open-http%0A%7C+as-records%0A%7C+match%28pattern%3D%22%28name%3D\%22DC%29\\.%28\\w%2A%3F%29\\.%28\\w%2A%3F%29%28\%22%29%22%2C+replacement%3D%22%241_%242_%243%244%22%29%0A%7C+match%28pattern%3D%22%28name%3D\%22DC%29\\.%28\\w%2A%3F%29%28\%22%29%22%2C+replacement%3D%22%241_%242%243%22%29%0A%7C+read-string%0A%7C+decode-html%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B%0A&fix=vacuum%28%29%0Ado+list%28path%3A%22html.head.meta%22%2C%22var%22%3A%22%24i%22%29%0A%0A++/%2A+Map+some+of+the+data+we+have+to+the+oersi+model%3A+%2A/%0A++%23+---------------id+--------%0A++copy_field%28%22%24i.DC_Identifier_URI%22%2C+%22id%22%29%0A%0A++%23+---------------name+--------%0A++copy_field%28%22%24i.citation_title%22%2C+%22name%22%29%0A%0A%0A++%23+---------------description+--------%0A++copy_field%28%22%24i.DC_Description%22%2C+%22description%22%29%0A%0A%0A++%23+---------------dateCreated+--------%0A++copy_field%28%22%24i.DC_Date_created%22%2C+%22dateCreated%22%29%0A%0A%23+---------------license+--------%0A++if+any_match%28%22%24i.DC_Rights%22%2C%22https%3A//creativecommons.org/.%2A%22%29%0A++++copy_field%28%22%24i.DC_Rights%22%2C+%22license.id%22%29%0A++end%0A%0Aend%0A%0Ado+list%28path%3A%22html.head.meta.DC_Creator_PersonalName%22%2C%22var%22%3A%22%24i%22%29%0A++%23+------+creator+---+%0A++set_array%28%22creator%5B%5D%22%29%0A++copy_field%28%22%24i%22%2C+%22creator%5B%5D.%24append.name%22%29%0Aend%0Aadd_field%28%22creator%5B%5D.%2A.type%22%2C+%22Person%22%29%0A%0Ado+list%28path%3A%22html.head.meta.DC_Language%22%2C%22var%22%3A%22%24i%22%29%0A++%23+------+inLanguage------%0A++set_array%28%22inLanguage%5B%5D%22%29%0A++copy_field%28%22%24i%22%2C+%22inLanguage%5B%5D.%24append%22%29%0Aend%0A%0Aretain%28%22@context%5B%5D%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22creator%5B%5D%22%2C%22contributor%5B%5D%22%2C%22sourceOrganization%5B%5D%22%2C+%22license%22%2C%22description%22%2C%22datePublished%22%2C%22dateCreated%22%2C%22dateModified%22%2C%22inLanguage%5B%5D%22%2C%22type%5B%5D%22%2C%22learningResourceType%5B%5D%22%2C%22keywords%5B%5D%22%2C%22about%5B%5D%22%2C+%22encoding%5B%5D%22%2C+%22publisher%5B%5D%22%2C+%22isPartOf%5B%5D%22%2C+%22mainEntityOfPage%5B%5D%22%2C%22conditionsOfAccess%22%2C%22duration%22%29%0A%0A&active-editor=fix)

**Comment by blackwinter** [comment]
> `set_array("creator[]")`
> `set_array("inLanguage[]")`

You're clearing these arrays during every iteration, and the last one (`<meta name="citation_publisher" content="Language Science Press"/>`) does not contain any relevant data for these fields.
