### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#295]
> > @fsteeg do you intend to release 0.4.1 to make this available?
> 
> I wasn't planning to do that, no, but we could.

I would allow to use all libraries with the cli right away and not have to wait for the next big release.
We could provide an easier "Getting started" and I could improve the tutorial

_Originally posted by @TobiasNx in https://github.com/metafacture/metafacture-fix/issues/275#issuecomment-1489974713_
            
Since the conferences are approaching and I would like to update the tutorial. Therefore I would like to suggest that we release the newest master as 0.4.1 since it includes all libraries in the runner.

**Comment by fsteeg** [comment]
> Since the conferences are approaching and I would like to update the tutorial. Therefore I would like to suggest that we release the newest master as 0.4.1 since it includes all libraries in the runner.

I will make a metafacture-fix 0.4.1 release based on metafacture-core 5.5.1-rc1, leaving the master dependencies on core (5.5.0) and the current dev version (0.5.0-SNAPSHOT) untouched.

**Comment by fsteeg** [comment]
Released metafacture-fix 0.4.1 based on metafacture-core 5.5.1-rc1, see:

https://github.com/metafacture/metafacture-fix/releases

**Comment by TobiasNx** [comment]
Thanks!
