### ISSUE TITLE
Provide array-agnostic way for addressing a subfield.

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#305]
In the presence of optionally repeated fields, there is no unified way of addressing a subfield. `field.subfield` only works if `field` _is not_ repeated (i.e., is an object internally), `field.*.subfield` only works if `field` _is_ repeated (i.e., is an array internally).

Alternatively, enable more/all functions to support the `field.subfield` syntax with repeated fields. E.g., `any_match()` does support it, `exists()` doesn't.

**Comment by TobiasNx** [comment]
Isn't this solvable with `do list`? I can iterate over simple and repeated field.

**Comment by blackwinter** [comment]
Yes, there are several workarounds, depending on the use case. And it's still inconvenient and error-prone.

**But**: I opened this issue under the assumption that Metafix's behaviour was incompatible with Catmandu. Which it [isn't](https://github.com/hbz/Catmandu/commit/760b4f9).
