### ISSUE TITLE
Publish vsc extension in visual studio marketplace fails

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-fix#310]
The upload of the new vsix file always fails.
Neither in the web interface https://marketplace.visualstudio.com/ () nor the command line tool vsce (`ERROR Failed request 401`) the upload works.

**Comment by katauber** [comment]
I tried today again to upload the new version and it worked. Do we need a review (sucessfully download and install) of this @fsteeg and @TobiasNx?

**Comment by fsteeg** [comment]
Not sure how to test, if I just install in VSCodium that won't use the correct marketplace, right?

**Comment by katauber** [comment]
Yes, you have to install in VS Code to use the right maketplace or download . But I think we don't need to test this. The extension itself was reviewed in #291. And you can see [here](https://marketplace.visualstudio.com/items?itemName=metafacture.fix) that there's version 0.2.0 available in the market place and not version 0.1.1 anymore.
