### ISSUE TITLE
Add catmandu function `log`

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#319]
We use it in our examples but it is not implemented yet.

Code Review: @fsteeg

**Comment by blackwinter** [comment]
The samples were taken from some Catmandu cheat sheet, IIRC. But I agree, we should implement the function.

**Comment by TobiasNx** [comment]
I context of OERSI we are intrested in this function. I do not know how complex it is to realize it.

**Comment by TobiasNx** [comment]
It seems that it cannot log an element value by default:

https://metacpan.org/pod/Catmandu::Fix::log

This would be a good feature. But it also could be solved if: #282 variables could be set by element values.
