### ISSUE TITLE
Lookup option default does not work

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#333]
See example here:

https://metafacture.org/playground/?flux=inputFile%0A%7C+open-file%0A%7C+as-records%0A%7C+decode-yaml%0A%7C+fix%28transformationFile%29%0A%7C+encode-yaml%0A%7C+print%0A%3B%0A&transformation=put_map%28%22typeMap%22%2C%0A++%22dog%22%3A+%22mammal%22%2C%0A++%22parrot%22%3A+%22bird%22%2C%0A++%22shark%22%3A+%22fish%22%0A%29%0A%0Acopy_field%28%22animal%22%2C%22type%22%29%0A%0Alookup%28%22type%22%2C%22typeMap%22%2C+_default%3A%22other%22%29%0A&data=---%0Aanimal%3A+dog%0A%0A---%0Aanimal%3A+parrot%0A%0A%0A---%0Aanimal%3A+shark%0A%0A---%0Aanimal%3A+crab

**Comment by TobiasNx** [comment]
okay, then this behaviour is different to catmandu:

`lookup("title","dict.csv", default:test)  # lookup 'marc' in dict.csv and replace the value or set it to 'test'`

See: https://librecat.org/Catmandu/

**Comment by TobiasNx** [comment]
and the documentation is incorrect: https://github.com/metafacture/metafacture-fix#lookup

**Comment by blackwinter** [comment]
The name difference is a Metamorph [relict](https://github.com/metafacture/metafacture-fix/blob/6cf83aea248de4da78576f5a389874178d4561c5/metafix/src/main/java/org/metafacture/metafix/FixMethod.java#L519), the behaviour should be adapted IMO.

**Comment by TobiasNx** [comment]
We decided at the Metafacture Meeting to still support the old MORPH way but without promoting it. By this we comply with Catmandus way without creating the confiusing in the documentation that there is an additional "old" way of providing default values.
