### ISSUE TITLE
Windows: Metafix-Runner sometimes complains that file path of runner is too long

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#371]
We have not found a solution yet.

```shell
$ C:\Users\USER\Downloads\metafix-runner-1.1.2\metafix-runner-1.1.2\bin\metafix-runner.bat
Die eingegebene Zeile ist zu lang.
Syntaxfehler.
```

Same for:
```shell
$ C:\Users\USER\Downloads\metafix-runner-1.1.2\metafix-runner\bin\metafix-runner.bat
$ C:\Users\USER\Downloads\metafix-runner\metafix-runner\bin\metafix-runner.bat
$ C:\Users\USER\Downloads\metafix-runner\metafix-runner-1.1.2\bin\metafix-runner.bat
$ C:\Users\USER\Downloads\metafix-runner-1.1.2\bin\metafix-runner.bat
```
The following works:

```shell
$ C:\Users\USER\Downloads\metafix-runner\bin\metafix-runner.bat
$ C:\Users\USER\Desktop\metafix-runner\bin\metafix-runner.bat
```

Workaround is to extract the metafix-runner without version in the download folder, the desktop or in the homefolder (maybe then with version would work too)

**Comment by TobiasNx** [comment]
Installed version of Metafacture Core works:

```
PS C:\Users\USER\git\metafacture-core> c:\Users\USER\git\metafacture-core\metafacture-runner\build\install\metafacture-core\flux.bat c:\Users\USER\Downloads\playground.flux
```

Release distribution seems to work too:

```
PS C:\Users\User\Downloads\metafacture-core-6.1.2-dist\metafacture-core-6.1.2-dist> C:\Users\User\Downloads\metafacture-core-6.1.2-dist\metafacture-core-6.1.2-dist\flux.bat
```

**Comment by TobiasNx** [comment]
From Fix repo:
```
./gradlew :metafix-runner:run --args="c:\Users\buelte\Downloads\playground.flux"
...
BUILD SUCCESSFUL in 1s
6 actionable tasks: 1 executed, 5 up-to-date
```
but:

```
./gradlew.bat :metafix-runner:run 
```

and
```
./gradlew :metafix-runner:run 
```

Have some kind of error, at first the seem to work and output the flux commands. But the build results in an error:

PS C:\Users\User\git\metafacture-fix> ./gradlew :metafix-runner:run                                                           

> Task :metafix-runner:run FAILED
Welcome to Metafacture
======================

{builtby=pc, version=6.1.2, timestamp=1721034436348}
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':metafix-runner:run'.
> Process 'command 'C:\Users\buelte\.gradle\jdks\eclipse_adoptium-11-amd64-windows.2\bin\java.exe'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
6 actionable tasks: 1 executed, 5 up-to-date
```

**Comment by blackwinter** [comment]
> Have some kind of error, at first the seem to work and output the flux commands. But the build results in an error:

So do the batch scripts. Flux [exits with an error code](https://github.com/metafacture/metafacture-core/blob/71c367c3576efbb38cc1c0f76d57b3baa66273ab/metafacture-runner/src/main/java/org/metafacture/runner/Flux.java#L63) when no file is given.

**Comment by blackwinter** [comment]
The difference between Metafix and Core is that the latter provides a bespoke batch script, while the former generates a generic one via Gradle's [Application plugin](https://docs.gradle.org/current/userguide/application_plugin.html). This error may theoretically hit both in the same way, but the Metafix script already contains a pretty long `CLASSPATH` variable which includes the path to the application directory (`APP_HOME`) a _bunch_ of times, thus easily exceeding the [command-line string limitation](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation).

In addition to that, the Metafix runner doesn't support the same configuration options as the Core runner (namely, [`java-options.conf`](https://github.com/metafacture/metafacture-core/blob/71c367c3576efbb38cc1c0f76d57b3baa66273ab/metafacture-runner/src/main/dist/config/java-options.conf)).

Both differences may hopefully become moot once Metafix gets integrated into Core.

**Comment by maipet** [comment]
Tested with the metafix-runner.bat in Windows: set the classpath with wildcard `set CLASSPATH=%APP_HOME%\lib\*` (Flux ran without the error message).  But I don't know whether this could cause problems elsewhere
(cf. https://stackoverflow.com/questions/1503708/problem-running-bat-file-on-windows-due-to-input-line-is-too-long resp. https://docs.oracle.com/javase/6/docs/technotes/tools/windows/classpath.html)

**Comment by dr0i** [comment]
@maipet right, if you manipulate `metafix-runner.bat` that change would be overwritten next time someone invokes `gradle`'s  `application` plugin, e.g. by running `./gradlew distZip`.  in ffa5b7a I followed https://stackoverflow.com/questions/32088966/gradle-generated-startscript-for-windows-produces-input-line-is-too-long for a solution.

**Comment by dr0i** [comment]
Also here - a big thx to all who have contributed here to fix this issue!
