### ISSUE TITLE
Multi-line comments

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#38]
At the moment you have to out-comment every line. Would be nice if FIX supports multi-line comments as FLUX does.

Extension show multiline.

**Comment by blackwinter** [comment]
Fix does support Java-style comments with `// ...` (single-line) and `/* ... */` (multi-line), in addition to its original Perl-style comments (`# ...`).

Has this been fixed without mentioning this issue? Or is it just a - potentially unintended - side effect of the Xtext implementation?

**Comment by blackwinter** [comment]
Can this issue be clarified - or closed if obsolete?

(Related to #4.)

**Comment by TobiasNx** [comment]
Can be closed. But I see is that the FLUX does not support multi-line `/*...*/`. Perhaps we need a ticket for that.
