### ISSUE TITLE
Add option to encode a string url-safe with `to_base64`

### ISSUE THREAD

**Issue by maipet** [metafacture/metafacture-fix#384]
In context of OERSI we need to encode  a string **URL**-safe to base64 (Base64url format) to reuse it later in an URL.

`https://www.youtube.com/watch?v=daLgsPSvD9A`

`to_base64` =>  `aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kYUxnc1BTdkQ5QQ==`

but url-safe would be: `aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1kYUxnc1BTdkQ5QQ==`

To enable url-safe base64 there should be an option in the [to_base64](https://github.com/metafacture/metafacture-fix/blob/3bb2b281a1e90f80e82c304726012e8c36ac255c/metafix/src/main/java/org/metafacture/metafix/FixMethod.java#L680-L685) function.

like this:
`to_base64("targetElement", url-safe:"true")`

**Comment by TobiasNx** [comment]
This should be an option in the to_base64 function.

**Comment by TobiasNx** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

I am not sure how to adjust the code to change the function by option url-safe:"true" to [`getUrlEncoder()`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getUrlEncoder--)

**Comment by TobiasNx** [comment]
https://github.com/metafacture/metafacture-fix/blob/3bb2b281a1e90f80e82c304726012e8c36ac255c/metafix/src/main/java/org/metafacture/metafix/FixMethod.java#L680-L685

@dr0i could you help? you introduced options to url_encode too. Maybe you have an idea. This should be introduced before the next release.

**Comment by dr0i** [comment]
Hm, not sure where your problem is. You can extract (using regex or so) the part of the URL you need to `base64`, base64 that String, and replace the substring in the URL with itt. If this is what you want?

**Comment by TobiasNx** [comment]
> Hm, not sure where your problem is. You can extract (using regex or so) the part of the URL you need to `base64`, base64 that String, and replace the substring in the URL with itt. If this is what you want?

Nope, that is not what I needed.
There is a specific way to encode strings url-safe to base64, this should be an option for the `to_base64` function called e.g. `url_safe`

**Comment by dr0i** [comment]
But this is exactly what the Fix-function `to_base64` already does, no ? : https://metafacture.org/playground/?flux=inputFile%0A%7Copen-file%0A%7Cas-records%0A%7Cdecode-json%0A%7Cfix%28transformationFile%29%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B%0A&transformation=%23+Transforms+the+value+to+base64+hash%0Ato_base64%28%22key%22%29%0A&data=%7B%0A++%22key%22+%3A+%22https%3A//www.youtube.com/watch%3Fv%3DdaLgsPSvD9A%22%0A%7D%0A

**Comment by TobiasNx** [comment]
> But this is exactly what the Fix-function `to_base64` already does, no ? : [metafacture.org/playground?flux=inputFile%0A%7Copen-file%0A%7Cas-records%0A%7Cdecode-json%0A%7Cfix%28transformationFile%29%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B%0A&transformation=%23+Transforms+the+value+to+base64+hash%0Ato_base64%28%22key%22%29%0A&data=%7B%0A++%22key%22+%3A+%22https%3A//www.youtube.com/watch%3Fv%3DdaLgsPSvD9A%22%0A%7D%0A](https://metafacture.org/playground/?flux=inputFile%0A%7Copen-file%0A%7Cas-records%0A%7Cdecode-json%0A%7Cfix%28transformationFile%29%0A%7Cencode-json%28prettyPrinting%3D%22true%22%29%0A%7Cprint%0A%3B%0A&transformation=%23+Transforms+the+value+to+base64+hash%0Ato_base64%28%22key%22%29%0A&data=%7B%0A++%22key%22+%3A+%22https%3A//www.youtube.com/watch%3Fv%3DdaLgsPSvD9A%22%0A%7D%0A)

output is:

```
 {
  "key" : "aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kYUxnc1BTdkQ5QQ=="
}
```

url-safe should be:

{
  "key" : "aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1kYUxnc1BTdkQ5QQ=="
}

See the underscore

**Comment by dr0i** [comment]
Ah: you don't mean:
> but url-safe would be: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1kYUxnc1BTdkQ5QQ==

but you mean:
"but url-safe should be: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1kYUxnc1BTdkQ5QQ=="

Mind 'would vs `should`.

**Comment by TobiasNx** [comment]
yes, exactly we would need optionally [`java.util.Base64.getUrlEncoder()`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getUrlEncoder--) instead of [`java.util.Base64.getEncoder`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getEncoder--)

**Comment by TobiasNx** [comment]
> Yeah, no, not _instead_of_ , but as an option, as you said. It's not an `either ... or` conjunction.

I added the adverb "optionally" and "for that" :)

I do not know how to write the code that when the option url-safe:"true" the method `to_base64`  utilizes [java.util.Base64.getUrlEncoder()](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getUrlEncoder--) otherwise it uses [java.util.Base64.getEncoder()](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html#getEncoder--).
