### ISSUE TITLE
Fix comment syntax in vs code/codium extension (VSC)

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#4]
Like `# This is a comment`, should be colored in vs code/codium extension.

**Comment by TobiasNx** [comment]
Would be nice if the comment syntax of FLUX and FIX would be identical.

**Comment by blackwinter** [comment]
The comment syntax was already supported when this issue was created (b375916). So what is there to do exactly? Does this issue refer to metafacture-playground ("web UI")?

**Comment by blackwinter** [comment]
Can this issue be clarified - or closed if obsolete?

**Comment by fsteeg** [comment]
It's actually about the vs code/codium extension, updated title and initial comment, thanks for the reminder!
