### ISSUE TITLE
Open VSX Listing: Sign the Publisher Agreement, package the license

### ISSUE THREAD

**Issue by spoenemann** [metafacture/metafacture-fix#41]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. 

Regrettably, if not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

In addition to the above, the published extension is missing a license. Please ensure to include a LICENSE file with the extension package, and add an entry `"license": "Apache-2.0"` to the package.json.

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. 
We look forward to continued innovation from you in 2021!

**Comment by katauber** [comment]
Extension must be published into [Open VSX Registry](https://open-vsx.org/) after merging, because the extension is build after merging into master.

**Comment by spoenemann** [comment]
Thanks for responding, @katauber! Now you could claim ownership of the `metafacture` namespace [as described in the Wiki](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace). This would mark your extensions as _verified_ and eliminate the warnings shown on the extension pages.
