### ISSUE TITLE
Add support for reset and sameEntity-attribute feature

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#46]
It seems that FIX at the moment does not support `reset` and `sameEntity` as attribute for collectors.

`sameEntity` and `reset` are only mentioned in https://github.com/metafacture/metafacture-fix/blob/71b484cfc6f74961404f35eba447d59f357f36a4/org.metafacture.fix.vsc/fix.tmLanguage in this repository

We need this in oersi to separate array and entity objects in transformations.

e.g.
Without sameEntity and reset:

```
do array("creator", flushWith: record)
 do entity("")
  map("author[].*.@type", "type")
  map("author[].*.name", "name")
 end
end
```

creates:

```JSON
    "creator": [
        {
            "type": "Person",
            "name": "RUVIVAL Team"
        },
        {
            "type": "Person",
            "name": "RUVIVAL Team",
            "type": "Person"
        },
        {
            "type": "Person",
            "name": "RUVIVAL Team",
            "type": "Person",
            "name": "Madiana Hazoume"
        }
    ]
```

Adding a version of `reset: true` and `sameEntity: true`  to `do entity("") `
should separate the creator like this:

```JSON
    "creator": [
        {
            "type": "Person",
            "name": "RUVIVAL Team"
        },
        {
            "type": "Person",
            "name": "Madiana Hazoume"
        }
    ]
```

**Comment by fsteeg** [comment]
This is about the old interim Fix implementation, closing.
