### ISSUE TITLE
replace using groups

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#49]
In FIX the `replace`-functions seems to use grouping different than regexp-functions:

While `regexp` calls a group with ${n} replace does not need the bracket. Is this a inconsistency in FIX or in Metafacture?

https://gitlab.com/oersi/oersi-etl/blob/54-idHoou/data/production/hhu.fix

```
/* Creation-Date comes in as "- recorded at 9/19/2012" */
do map("*.span.watch-information-date produced", "dateCreated")
  regexp(match: "- recorded at \\d{1,2}}/\\d{1,2}}/\\d{4}")
  replace(pattern: "(\\d)/(\\d+)/(\\d\\d\\d\\d)", with: "0$1/$2/$3")
  replace(pattern: "(\\d+)/(\\d)/(\\d\\d\\d\\d)", with: "$1/0$2/$3")
  replace(pattern: "- recorded at (\\d\\d)/(\\d\\d)/(\\d\\d\\d\\d)", with: "$3-$1-$2")
end
```

**Comment by fsteeg** [comment]
This is about the old interim Fix implementation, closing.
