### ISSUE TITLE
Allow linebreak in lookup

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#50]
At the moment only 

```
do map("audience[].*.educationalRole", "@educationalAudienceRole")
  lookup("Lehrer*in": "teacher", "Schüler*innen": "student", "Student*in": "student")
end
```
is possible.
For lookups and also for things like setReplace line-breaks should be possible like the following example:
```

do map("audience[].*.educationalRole", "@educationalAudienceRole")
  lookup(
    "Lehrer*in": "teacher",
    "Schüler*innen": "student",
    "Student*in": "student"
  )
end
```

**Comment by fsteeg** [comment]
Functional review: @TobiasNx
Code review: @katauber

**Comment by fsteeg** [comment]
Deployed to [test.metafacture.org/playground/](https://test.metafacture.org/playground/?data=1%7Bn%3A+Goethe%7D%0A2%7Bn%3A+Schiller%7D%0A3%7Bn%3A+M%C3%BCller%7D&flux=as-lines%0A%7Cdecode-formeta%0A%7Cfix%0A%7Cencode-json&fix=lookup%28n%2C%0A++%27Goethe%27%3A+%27118540238%27%2C%0A++%27Schiller%27%3A+%27118607626%27%2C%0A++%27__default%27%3A+%274428933-9%27%29&morph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0A%3Cmetamorph+xmlns%3D%22http%3A//www.culturegraph.org/metamorph%22+xmlns%3Axsi%3D%22http%3A//www.w3.org/2001/XMLSchema-instance%22%0A%09version%3D%221%22%3E%0A%09%3Crules%3E%0A%09%09%3Cdata+source%3D%22_id%22+name%3D%22id%22/%3E%0A%09%09%3Cdata+source%3D%22a%22+name%3D%22title%22/%3E%0A%09%09%3Ccombine+value%3D%22%24%7Bfirst%7D+%24%7Blast%7D+aus+%24%7Bplace%7D%22+name%3D%22author%22%3E%0A%09%09%09%3Cdata+source%3D%22b.v%22+name%3D%22first%22+/%3E%0A%09%09%09%3Cdata+source%3D%22b.n%22+name%3D%22last%22+/%3E%0A%09%09%09%3Cdata+source%3D%22c%22+name%3D%22place%22+/%3E%0A%09%09%3C/combine%3E%0A%09%3C/rules%3E%0A%3C/metamorph%3E%0A&active-editor=fix).

**Comment by TobiasNx** [comment]
Ah cool, you used the playground to present the function. All in all, +1 concerning the functionality.

I was wondering how to use the lookup in the newer fix version.

I have two questions:

- Since this is a new feature to the new fix-function-world where do we document the functions of fix. Since fix will grow quickly in the next few weeks I think we should be document also for the user perspective from now on. So that documenting will not be a big task at a later stage.

- Concerning the attributes and options stated in lookuo this brings me to a broader topic: Is there a rule when to use double/single quotation marks or not. The path is not using any, the values-pair in the lookup list does. Is there a rule/concvention in catmandu how to do this.

**Comment by fsteeg** [comment]
> I have two questions

Since both questions are independent of the the issue fixed here, I think these should be move to separate issues.
