### ISSUE TITLE
Support full Flux with URL input in web UI

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#6]
To run workflows like:

`"https://www.hoou.de/materials/tutorial-lernen-lernen"` | `open-http` ...

See also https://github.com/metafacture/metafacture-core/issues/312

**Comment by fsteeg** [comment]
Deployed to http://test.lobid.org/fix:

Data: leave empty
Flux:
`"https://www.hoou.de/materials/tutorial-lernen-lernen"|open-http|decode-html|fix|encode-json(prettyPrinting="true")`
Fix:
`map(html.head.title.value,title)
map(html.body.div.div.div.div.div.div.div.p.value, description)`

**Comment by acka47** [comment]
Works great, also in Chromium.

**Comment by fsteeg** [comment]
Merged, closing. See https://github.com/metafacture/metafacture-fix/commit/2e20b99879d5f56e7b9398128061d37436cb693b.
