### ISSUE TITLE
Agree on a single Checkstyle suppression mechanism

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#62]
Came up in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r737447591. I seem to remember that something was not possible with the original `checkstyle-disable-line` when adding support for `@SuppressWarnings` in https://github.com/metafacture/metafacture-fix/commit/d70d5d3b1405ab845c90f5ed9e4b76a52d73db02. Maybe I didn't see a way to suppress `MultipleStringLiterals` for the entire class? See https://github.com/metafacture/metafacture-fix/pull/60#discussion_r737447591 for other pro/cons of both approaches.

**Comment by blackwinter** [comment]
Copying previous discussion for better overview:

---

Suggesting switching to `@SuppressWarnings` in https://github.com/metafacture/metafacture-fix/pull/60/commits/ea54a0ec96a2bb90a47f057f70c05c83d563fd82, as it's the standard Java suppression mechanism.

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r741966312_

---

But it's also limited in where it can appear! Now the check is suppressed in the whole method `org.metafacture.metafix.InterpreterTest.shouldInterpretNested()`; should we - unintentionally - add another "magic number", we wouldn't notice.

Also:

1. At least in our case, check violations are errors, not warnings.
2. We can't limit the number of allowed exceptions (currently two with `checkstyle-disable-line`).
3. The `SuppressWithNearbyCommentFilter` setting should be removed if we're no longer using it.

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r741975505_

**Comment by fsteeg** [comment]
Discussed: switch to `checkstyle-disable-line` comments for consistency with metafacture-core, disable `MultipleStringLiterals` checks for tests.
