### ISSUE TITLE
Consistent handling of repeated fields / arrays

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#65]
Explicit arrays (e.g. in JSON input) vs. explicit / repeated values (e.g. in XML input).

Field names like:

`metadata.mods.identifier.value` vs.
`metadata.mods.identifier.*.value` vs.
`metadata.mods.identifier[].*.value`

See:

- https://github.com/metafacture/metafacture-fix/issues/35#issuecomment-932020224
- https://github.com/metafacture/metafacture-fix/pull/60#discussion_r738381260

**Comment by blackwinter** [comment]
Copying previous discussion for better overview:

---

I have to admit, I find this behaviour highly debatable. What's the rationale? I guess I want to have full control over the output I'm building, not have Metafix decide that it knows better what I wanted?

Granted, I don't have an example at hand right now. Maybe I'm overreacting. Certainly feels iffy, though...

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r738381260_

---

Yeah, the whole topic of repeated values / arrays needs work. I've opened https://github.com/metafacture/metafacture-fix/issues/65 for that.

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/pull/60#discussion_r743709464_

**Comment by fsteeg** [comment]
From discussion:

- Don't add `[]` automatically, leave it to the user to set that
- Add index number as entity names for arrays of objects
- Support `*` as placeholder for the index number (and general wildcard support)

**Comment by fsteeg** [comment]
Functional review: @TobiasNx, code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
There is one difficulty that pop in my head.

If we have multiple records and a field is repeatable. But in a couple of records the field exist 1-time and in other n+1 times.
The fix would have to handle this differently since it would have to operate once with a list bind and one with the direct operation on the field since the notation would be different:  `test.*.feld` (when n+1 occurences) vs. `test.feld` (1 occurence)

**Comment by blackwinter** [comment]
Indeed, that's what I'm concerned about too. But you can always iterate over the parent element, can't you? (`do list(path:test, var:loop)` => do something with `loop.feld`)

**Comment by TobiasNx** [comment]
> Indeed, that's what I'm concerned about too. But you can always iterate over the parent element, can't you? (`do list(path:test, var:loop)` => do something with `loop.feld`)

`do list` only works with arrays so unfortunately this would not work. the bind to repeat things on a hash/element is `do each`

Also if you want to select the path for an array in an other field/array you need the index-number or wildcard https://github.com/LibreCat/Catmandu/wiki/Paths#wildcards:

`record.test.feld.*`

**Comment by TobiasNx** [comment]
It seems that catmandu is behaving the same way:
https://github.com/TobiasNx/Catmandu-Testing/tree/master/repeatable_fields_xml

It could be that the specific importer change tha behaviour if in a specific format like MODS a field is repeatable or not.

**Comment by TobiasNx** [comment]
I investigated this a little further: https://github.com/TobiasNx/Catmandu-Testing/tree/master/repeatable_fields_xml

Catmandu converts general formats like XML as follow:
- single field => key-value-pair
- repeated field => list

But specific importers like MODS or the OAI importer that converts Dublin Core create lists by default for fields that are defined as repeatable fields in the format/schema.

**Comment by fsteeg** [comment]
Pre-published current state as `0.2.0-rc6`, used in [oersi-etl!99](https://gitlab.com/oersi/oersi-etl/-/merge_requests/99). See basic checklist from our meeting in https://github.com/metafacture/metafacture-fix/issues/65#issuecomment-965013642. I think this issue is too broad and should be split up into / replaced by smaller issues (e.g. #66, #80).

Assigning @TobiasNx for functional review; see also the discussion at https://github.com/metafacture/metafacture-fix/pull/78#issuecomment-982518710 about a possible better process for providing and implementing specific use cases.

**Comment by TobiasNx** [comment]
I think it will be best if I will create small use cases/test cases that need to be handled in https://gitlab.com/oersi/oersi-etl/-/tree/FunctionalReview/data/experimental

Perhaps we could have a separate metafacture instance only for testing where we could collect test scenarios besides the OERSI context?

**Comment by TobiasNx** [comment]
@blackwinter what should I do here?

**Comment by blackwinter** [comment]
> what should I do here?

I don't know. This issue has status "Review" and you're the reviewer. If the status is no longer appropriate it should be updated, I guess.

**Comment by TobiasNx** [comment]
I think this is resolved in context of: https://github.com/metafacture/metafacture-fix/issues/109

**Comment by TobiasNx** [comment]
I close this ticket, we can reopen it, if we need.
