### ISSUE TITLE
Align subproject layout with metafacture-core

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#71]
BTW (in the context of 683c247): Is there a reason why we don't just rename the subproject directories, mimicking the layout in metafacture-core?

- `org.metafacture.fix/` -> `metafix/` (no need to override the project name anymore)
- `org.metafacture.fix.ide/` -> `metafix-ide/`
- `org.metafacture.fix.vsc/` -> `metafix-vsc/`
- `org.metafacture.fix.web/` -> `metafix-web/`

_Originally posted by @blackwinter in https://github.com/metafacture/metafacture-fix/issues/16#issuecomment-966932921_

---

Sounds good. The current naming is the Xtext/Eclipse convention, but it should work to set up MWE workflow etc. for the simpler directories/names.

_Originally posted by @fsteeg in https://github.com/metafacture/metafacture-fix/issues/16#issuecomment-966979880_

**Comment by blackwinter** [comment]
I have no idea what kind of pitfalls there might be w.r.t. Eclipse or Xtext/MWE workflow. Shall I just make the change and you check it during review? Or do you rather want to do it yourself?

**Comment by fsteeg** [comment]
> Shall I just make the change and you check it during review?

Yes, maybe it's not even an issue at all.
