### ISSUE TITLE
Documentation concepts and function of fix

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#73]
Since lookup with internal value is a new feature to the new fix-function-world where do we document the functions of fix. Since fix will grow quickly in the next few weeks I think we should be document also for the user perspective from now on. So that documenting will not be a big task at a later stage.

_Originally posted by @TobiasNx in https://github.com/metafacture/metafacture-fix/issues/50#issuecomment-968637211_

**Comment by fsteeg** [comment]
Long-term we should generate useful Javadoc, including the function enums. Short-term, @TobiasNx will create a simple manually maintained list of functions, in a *.md file.

Functional review: @fsteeg & @blackwinter

**Comment by blackwinter** [comment]
> in a *.md file.

Could this simply be the `README.md` (for now)?
