### ISSUE TITLE
Error is shown but flux does not break

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#79]
```
# -----------license----------
copy_field("metadata.mods:mods.mods:accessCondition.xlink:href","license.id")
lookup("license.id", ,"data/maps/duepublico-licenses.tsv","sep_char":"\t") 
```

Results in:
```
$ ./gradlew run --args '/home/tobias/git/oersi-etl/data/experimental/duepub-metafacture.flux' 

> Task :run
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/tobias/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.21/7238b064d1aba20da2ac03217d700d91e02460fa/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/tobias/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.21/be4b3c560a37e69b6c58278116740db28832232c/slf4j-simple-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2021-11-30 13:50:42 [INFO] [ETL:127] Running /home/tobias/git/oersi-etl/data/experimental/duepub-metafacture.flux with 5 arguments (configure output details in log4j.properties)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/tobias/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/3.0/9d84f15fe35e2c716a02979fb62f50a29f38aefa/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-11-30 13:50:44 [WARN] [XtextValidator:33] The FixStandaloneSetup file '/tmp/metafix11085895098891549246.fix' has 1 issue:
2021-11-30 13:50:44 [WARN] [XtextValidator:36] - ERROR: no viable alternative at input ',' (78:20)
2021-11-30 13:50:44 [INFO] [ETL:158] Import channel duepub-metafacture.flux, SUCCESS: 0, FAIL-PROCESS: n/a, FAIL-VALIDATION: n/a, FAIL-WRITE: 0, DURATION: 00:00:02

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```

Still transformation is processed and json is returned.

**Comment by blackwinter** [comment]
We could change [`XtextValidator.getValidatedResource()`](https://github.com/metafacture/metafacture-fix/pull/60/commits/6393b4d8a41e3ee8d09f30db50fe2c99b35556dc#diff-356f7e47f43b55187d1de53807ba7193fcf7cfe85c3ce1549d9a802caacc1a27R64) to throw an exception when invalid. Just a `RuntimeException`, or a `IllegalArgumentException`, or something more specific?

**Comment by TobiasNx** [comment]
Also https://github.com/metafacture/metafacture-fix/issues/126

> https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/41e403a51e4a987192f27fd246c67c24725119b9/data/testing/missingErrorWhenTrailingEndIsMissing
> 
> instead of an error, a missing end results in passing through all input data.
> 
> Expected: error Is: input-file

**Comment by fsteeg** [comment]
Functional review: @TobiasNx
Code review: @blackwinter / @fsteeg

**Comment by TobiasNx** [comment]
When testing following test newly break:

- ./data/testing/missingErrorWhenTrailingEndIsMissing/missingError.flux
- ./data/testing/flattening/flatten.fix
- ./data/approved/rename/rename.flux
- ./data/approved/append/append.flux
- ./data/approved/prepend/prepend.flux

These also broke before:

- ./data/approved/join_field/join_field_xml.flux + 
- ./data/testing/moveToNewOwnSubfield/moveToNewOwnSubfield.flux +
- ./data/testing/copyFieldWithPipe/pipe.flux +

I do not understand why flatten, rename, append and prepend - tests break.

**Comment by TobiasNx** [comment]
Error is: `"ERROR: mismatched character '<EOF>' expecting '\n'"` (Thanks to @blackwinter )

Is this error needed? Is the trailing linebreak really necessary?

**Comment by blackwinter** [comment]
I guess, this question has two parts:

1. _Can_ we configure the grammar to accept files without a final newline?
2. _Should_ we do this?

The first part is probably best answered by @fsteeg. As for the latter: I for one am firmly against it; each line in a file, even the final one, should be terminated by a newline.

**Comment by TobiasNx** [comment]
I am okay, if we keep it. 
Perhaps we should be consistent, if a function is at the end the error does not appear only if the last line is a comment.
Imo the error should therefore also appear when the function is at the end.

**Comment by TobiasNx** [comment]
Btw.: +1 on the issue.

**Comment by blackwinter** [comment]
Alright, thanks! :)
