### ISSUE TITLE
Use HTTP POST for data in web UI

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture-fix#8]
https://github.com/metafacture/metafacture-fix/blob/603cf445644ce521ada2670530d30a9434faa93d/org.metafacture.fix.parent/org.metafacture.fix.web/src/main/webapp/index.html#L47

**Comment by fsteeg** [comment]
Deployed support for larger input using POST to http://test.lobid.org/fix/:

- Data: paste source of https://www.hbz-nrw.de/produkte/linked-open-data as data
- Flux: `html-to-xml|decode-xml|handle-generic-xml("html")|fix|encode-json(prettyPrinting="true")`
- Fix: `map(_else)`

**Comment by acka47** [comment]
Could I also post this via curl? Could you provide me with the command?

**Comment by acka47** [comment]
Regarding the actual behaviour: It is working without problems in Firefox but not in Chromium (Version 79.0.3945.79 (Official Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)). It seems to have problems with the big slice of text in the "data" field and won't process.

**Comment by acka47** [comment]
> Regarding the actual behaviour: It is working without problems in Firefox but not in Chromium 

For now it would be ok for me if it only runs in Firefox as the UI is transitional anyway.

**Comment by fsteeg** [comment]
> Could I also post this via curl? Could you provide me with the command?

This is what works right now:

`curl -X POST --data-urlencode 'flux=html-to-xml|decode-xml|handle-generic-xml("html")|fix|encode-json(prettyPrinting="true")' --data-urlencde 'fix=map(_else)' --data-urlencode 'data=<p class="header">hi</p>' http://test.lobid.org/fix/xtext-service/run`

If we actually want to post JSON data (as we discussed offline recently), we should open a new issue.
> For now it would be ok for me if it only runs in Firefox as the UI is transitional anyway.

Plus, after implementing https://github.com/metafacture/metafacture-fix/issues/6, we could use input URLs in the UI instead of pasting data.

**Comment by acka47** [comment]
+1
