### ISSUE TITLE
Array of strings handling not working

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#82]
Separated this issue from #80 to create smaller issues. 

Fix is not able to operate with array of strings, It cannot create new ones and cannot refrence existing once.

It should be able to refrence a string/value with e.g.: `test.$append`, `test.*` See: http://librecat.org/Catmandu/#wildcards
It would operate on them as items. (This could also be true for handling entire objects as items.)

[Broken workflow](
https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfStringimals%22%3A+%5B%22cat%22%2C%22dog%22%2C%22fox%22%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfStringimals%5B%5D.%24append%22%2C%22duck%22%29&active-editor=fix)

It works with a subfield: [here](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfStringimals%22%3A+%5B%22cat%22%2C%22dog%22%2C%22fox%22%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfStringimals%5B%5D.%24append.test%22%2C%22duck%22%29&active-editor=fix)

It could be that this issue is too connected to #80 then we should close it.

**Comment by fsteeg** [comment]
Deployed to test, see [your example](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfStringimals%22%3A+%5B%22cat%22%2C%22dog%22%2C%22fox%22%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfStringimals%5B%5D.%24append%22%2C%22duck%22%29&active-editor=fix).

**Comment by TobiasNx** [comment]
It seems to work with string: +1

But is does not seem to work with array of objects where you add a new object: 
[here](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24append.name%22%2C%22duck%22%29&morph=&active-editor=fix )

Should be handled in new ticket.

**Comment by fsteeg** [comment]
> But is does not seem to work with array of objects where you add a new object

Handled this here / in #87 as it's very related. Deployed to test: [issue on prod](https://metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24append.name%22%2C%22duck%22%29&morph=&active-editor=fix), [fixed on test](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24append.name%22%2C%22duck%22%29&morph=&active-editor=fix).

**Comment by blackwinter** [comment]
@TobiasNx: Can you assign me when #87 is ready to be merged?

**Comment by TobiasNx** [comment]
Somehow the playground examples do not work for me right now. Perhaps due to changes in test.

But I also tried it with these tests here with fix build from 82-append with `./gradlew publishToMavenLocal:`
https://gitlab.com/oersi/oersi-etl/-/tree/FunctionalReview/data/experimental/appendArrays

Now non of my examples seems to work. Did I do anything wrong?

**Comment by fsteeg** [comment]
I don't understand, still looks good to me, as linked in https://github.com/metafacture/metafacture-fix/issues/82#issuecomment-989705046:

[issue on prod](https://metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24append.name%22%2C%22duck%22%29&morph=&active-editor=fix)

```
{
  "arrayOfObjectimals" : [ {
    "name" : "cat"
  }, {
    "name" : "dog"
  }, {
    "name" : "fox"
  }, "duck" ]
}
```

[fixed on test](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24append.name%22%2C%22duck%22%29&morph=&active-editor=fix)

```
{
  "arrayOfObjectimals" : [ {
    "name" : "cat"
  }, {
    "name" : "dog"
  }, {
    "name" : "fox"
  }, {
    "name" : "duck"
  } ]
}

**Comment by TobiasNx** [comment]
> Deployed to test, see [your example](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfStringimals%22%3A+%5B%22cat%22%2C%22dog%22%2C%22fox%22%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfStringimals%5B%5D.%24append%22%2C%22duck%22%29&active-editor=fix).

It is this example, that does not work anymore.

**Comment by fsteeg** [comment]
Alright, I think the string cases are now all working: [one](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24append.name%22%2C%22duck%22%29&morph=&active-editor=fix), [two](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfStringimals%22%3A+%5B%22cat%22%2C%22dog%22%2C%22fox%22%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfStringimals%5B%5D.%24append%22%2C%22duck%22%29&active-editor=fix), [three](https://test.metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A%5B%0A%09%09%09%22dog%22%2C%0A%09%09%09%22cat%22%0A%09%5D%2C%0A%09%22others%22%3A+%22human%22%2C%0A%09%22fictional%22%3A+%22unicorn%22%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22others%22%2C+%22animals%5B%5D.%24append%22%29%0A%0Amove_field%28%22fictional%22%2C+%22animals%5B%5D.%24append%22%29%0A%0Aadd_field%28%22animals%5B%5D.%24append%22%2C+%22earthworm%22%29&morph=&active-editor=fix).

**Comment by TobiasNx** [comment]
Looks good now +1
