### ISSUE TITLE
Add support for Metamorph wildcards.

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#89]
While Fix/Catmandu has its own variant of [wildcards](https://librecat.org/Catmandu/#wildcards) (which are only partially implemented currently), we also need [Metamorph wildcards](https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide#addressing-pieces-of-data) to be available (both are mutually compatible; see also [`WildcardTrie`](https://github.com/metafacture/metafacture-core/blob/1ecaa75a9c5c5f36ff40a76ad42872252576a297/metafacture-commons/src/main/java/org/metafacture/commons/tries/WildcardTrie.java)/[`SimpleRegexTrie`](https://github.com/metafacture/metafacture-core/blob/1ecaa75a9c5c5f36ff40a76ad42872252576a297/metafacture-commons/src/main/java/org/metafacture/commons/tries/SimpleRegexTrie.java)).

An alternative might be to implement [specialized fixes](https://metacpan.org/pod/Catmandu::MARC#MODULES) with [MARC paths](https://librecat.org/Catmandu/#marc-mab-pica-paths) instead (see also [MARCspec](https://marcspec.github.io/MARCspec/marc-spec.html)).

Functional review: @TobiasNx
Code review: @fsteeg

**Comment by TobiasNx** [comment]
I think it should be highlighted that the function of metafacture wildcards are different to the catmandu wildcards.

Catmandu Wildcards ["are used to point to relative positions or many positions in a list".](https://github.com/metafacture/metafacture-core/wiki/Metamorph-User-Guide#addressing-pieces-of-data).

Metafactue are used to target multiple variations of path names not only the position in a list.

**Comment by blackwinter** [comment]
> Metafactu[r]e [wildcards] are used to target multiple variations of path names not only the position in a list.

Indeed, thank you.

**Comment by TobiasNx** [comment]
I added a couple of functional test, they seem fine. Except for Test 2. This seems to be an odd behaviour concerning copy_field. Instead of overwriting the field "animal" it creates an object with two instances.

https://gitlab.com/oersi/oersi-etl/-/tree/FunctionalReview/data/experimental/wildCardTest

**Comment by blackwinter** [comment]
Thanks! So that's a :+1: from you w.r.t. wildcard support?

**Comment by TobiasNx** [comment]
I added a sixt test. That also looks if a asteriks truncation also includes all the subordinated fields and values of arrays, but it seems not. Perhaps that is something that we do not need, but this was supported by metafacture morph.

https://gitlab.com/oersi/oersi-etl/-/blob/FunctionalReview/data/experimental/wildCardTest/wildcard_test6.flux

If that is something for a later stage or something we do not need I would say +1.

**Comment by blackwinter** [comment]
> That also looks if a asteriks truncation also includes all the subordinated fields and values of arrays, but it seems not.

That's right, I didn't do this - more or less - intentionally. It would break compatibility with Fix/Catmandu (Metamorph-`*` would have a different meaning than Fix-`*`) and it's also not required for us ATM.

> Perhaps that is something that we do not need, but this was supported by metafacture morph.

This will be our eternal dilemma ;) It's impossible to merge two mature projects of any kind without some losses. We can try to reconcile wherever possible as much as possible, but it's never going to be perfect.

**Comment by TobiasNx** [comment]
> > Perhaps that is something that we do not need, but this was supported by metafacture morph.
> 
> This will be our eternal dilemma ;) It's impossible to merge two mature projects of any kind without some losses. We can try to reconcile wherever possible as much as possible, but it's never going to be perfect.

It does not have to be an dilemma, sometimes is is good :D. It is something that I did not like in "old" metafacture morph.

**Comment by blackwinter** [comment]
FTR: Wildcard/regex matching does not (currently) extend to _virtual_ fields (#63). They always have to be selected explicitly.
