### ISSUE TITLE
Support path-wildcards (`$append`, `$prepend`, `$last`, `$first`) for whole objects

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#92]
Adding and copying sub-fields with `$append` seem to work. But copying and moving whole objects into an array with `$append` seems not to work:
https://gitlab.com/oersi/oersi-etl/blob/2a05f299ebb6346cf59b4d1ad7b8930531a9a834/data/experimental/appendArrays/test_append_object.flux

[See here in the Playground too](
https://metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A%5B%0A%09%09%09%7B%22animal%22%3A+%22dog%22%7D%2C%0A%09%09%09%7B%22animal%22%3A+%22cat%22%7D%0A%09%5D%2C%0A%09%22others%22%3A+%7B%22animal%22%3A+%22human%22%7D%2C%0A%09%22fictional%22%3A+%7B%22animal%22%3A+%22unicorn%22%7D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22others%22%2C+%22animals%5B%5D.%24append%22%29%0A%0Amove_field%28%22fictional%22%2C+%22animals%5B%5D.%24append%22%29%0A%0Aadd_field%28%22animals%5B%5D.%24append.animal%22%2C+%22earthworm%22%29&morph=&active-editor=fix)

_Originally posted by @TobiasNx in https://github.com/metafacture/metafacture-fix/issues/80#issuecomment-993764171_

It is related to MR #87 and issue #82 (but for strings) which deals with appending.
If we decide that this should be solved in another MR we should exclude the failing test for complex appending objects.

```
{
	"animals":[
			{"animal": "dog"},
			{"animal": "cat"},
                        {"animal": "human"},
                        {"animal": "unicorn"},
                       {"animal": "earthworm"}
	],
	"others":  {"animal": "human"}
}
```

**Comment by TobiasNx** [comment]
See test: https://github.com/TobiasNx/fix-FunctionalReview-Testing/commit/a45d39c5b9a22ed458c4f1542d2b0b41ff9d7ab6

Expected:
```
{
	"animals":[
			{"animal": "dog"},
			{"animal": "cat"},
			{"animal": "human"},
			{"animal": "unicorn"},
			{"animal": "earthworm"}
	],
	"others": {"animal": "human"}
} 
```

Is:
```

{
  "animals" : [ {
    "animal" : "dog"
  }, {
    "animal" : "cat"
  }, {
    "animal" : "earthworm"
  } ],
  "others" : {
    "animal" : "human"
  }
}
```

**Comment by TobiasNx** [comment]
Added also a prepend function to test: https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/appendArray_objects

**Comment by fsteeg** [comment]
Will revisit after #102.

**Comment by blackwinter** [comment]
Integration tests:

- [copy_fieldPrependObjectToArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldPrependObjectToArrayOfObjects)
- [move_fieldPrependObjectToArrayOfObjects](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldPrependObjectToArrayOfObjects)
