### ISSUE TITLE
Catmandu-Path-Wildcard-Support: `$prepend`

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#93]
Test for prepend:
For array of strings:
[Here](https://metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A%5B%0A%09%09%09%22dog%22%2C%0A%09%09%09%22cat%22%0A%09%5D%2C%0A%09%22others%22%3A+%22human%22%2C%0A%09%22fictional%22%3A+%22unicorn%22%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22others%22%2C+%22animals%5B%5D.%24prepend%22%29%0A%0Amove_field%28%22fictional%22%2C+%22animals%5B%5D.%24prepend%22%29%0A%0Aadd_field%28%22animals%5B%5D.%24prepend%22%2C+%22earthworm%22%29&morph=&active-editor=fix)

Output should be:
```
{
	"animals":[
                        "earthworm".
                        "unicorn",
                        "human",
			"dog",
			"cat"
	],
	"others": "human"
}
```

For array of objects:
[Here](https://metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A%5B%0A%09%09%09%7B%22animal%22%3A+%22dog%22%7D%2C%0A%09%09%09%7B%22animal%22%3A+%22cat%22%7D%0A%09%5D%2C%0A%09%22others%22%3A+%7B%22animal%22%3A+%22human%22%7D%2C%0A%09%22fictional%22%3A+%7B%22animal%22%3A+%22unicorn%22%7D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22others%22%2C+%22animals%5B%5D.%24prepend%22%29%0A%0Amove_field%28%22fictional%22%2C+%22animals%5B%5D.%24prepend%22%29%0A%0Aadd_field%28%22animals%5B%5D.%24prepend.animal%22%2C+%22earthworm%22%29&morph=&active-editor=fix)

Output should be:

```
{
	"animals":[
                        {"animal": "earthworm"}
                        {"animal": "unicorn"},
                        {"animal": "human"},
			{"animal": "dog"},
			{"animal": "cat"}
	],
	"others": {"animal": "human"}
}
```

**Comment by TobiasNx** [comment]
Added a test scenario: https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/prependArrays_strings

**Comment by blackwinter** [comment]
See also #92.

**Comment by fsteeg** [comment]
Will revisit after 102.

**Comment by blackwinter** [comment]
Integration tests:

- [copy_fieldPrependAndCreateArray](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/copy_fieldPrependAndCreateArray)
- [move_fieldPrependAndCreateArray](https://github.com/metafacture/metafacture-fix/tree/master/metafix/src/test/resources/org/metafacture/metafix/integration/record/fromJson/toJson/move_fieldPrependAndCreateArray)
