### ISSUE TITLE
Catmandu-Wildcard-Support: $first, $last

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#94]
It seems that `$first` and `$last` is not supported yet. (Catmandu is not consistent if `$first`, `$last` or `$start`, `$end` is the right wildcard. See: https://github.com/LibreCat/Catmandu/issues/387) (Update 20.12.: `$first` and `$last` are the correct ones: [See here ](https://github.com/LibreCat/Catmandu/issues/387#issuecomment-997658004))

[Example here](https://metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24first.kind%22%2C%22angry%22%29%0Aadd_field%28%22arrayOfObjectimals%5B%5D.%24last.kind%22%2C%22nice%22%29&morph=&active-editor=fix)

Output should be:
```
{
    "arrayOfObjectimals": [
                               {"name": "cat", "kind": "angry"},
                               {"name": "dog"},
                               {"name": "fox", "kind": "nice"}
                          ]
}
```

**Comment by TobiasNx** [comment]
The behaviour in the example suggests that `$last` acts the same way as `$append`.

**Comment by fsteeg** [comment]
Deployed to test, see: [https://test.metafacture.org/playground/?data=...](https://test.metafacture.org/playground/?data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=add_field%28%22arrayOfObjectimals%5B%5D.%24first.kind%22%2C%22angry%22%29%0Aadd_field%28%22arrayOfObjectimals%5B%5D.%24last.kind%22%2C%22nice%22%29&morph=&active-editor=fix)

**Comment by TobiasNx** [comment]
[Seems to work with move_field/copy_field with strings](https://test.metafacture.org/playground/?flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22animalType%22%2C+%22arrayOfObjectimals%5B%5D.%24first.animalType%22%29%0Amove_field%28%22animalType%22%2C+%22arrayOfObjectimals%5B%5D.%24last.animalType%22%29&data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%2C%0A++++%22animalType%22%3A+%22real%22%0A%7D&active-editor=fix)

[Seems not to work with objects.](
https://test.metafacture.org/playground/?flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22animalType%22%2C+%22arrayOfObjectimals%5B%5D.%24first.animalType%22%29%0Amove_field%28%22animalType%22%2C+%22arrayOfObjectimals%5B%5D.%24last.animalType%22%29&data=%7B%0A++++%22arrayOfObjectimals%22%3A+%5B%7B%22name%22%3A+%22cat%22%7D%2C%7B%22name%22%3A+%22dog%22%7D%2C%7B%22name%22%3A+%22fox%22%7D%5D%2C%0A++++%22animalType%22%3A+%7B%0A++++++++%22kind%22%3A+%22mammel%22%2C%0A++++++++%22existence%22%3A+%22real%22%0A++++%7D%0A%7D&active-editor=fix)
