### ISSUE TITLE
do list with JSON Array not working

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#95]
It seems that the `do list`-Bind is not working with JSON-Arrays.

[See here](https://metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A+%5B%0A%09%09%7B%0A%09%09%09%22name%22%3A+%22Jake%22%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09%22name%22%3A+%22Blacky%22%0A%09%09%7D%0A%09%5D%0A%7D&flux=PG_DATA%0A%7Cas-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=do+list%28%22animals%5B%5D%22%29%0A++++copy_field%28%22name%22%2C+%22BAME%22%29%0Aend&active-editor=fix)

**Comment by blackwinter** [comment]
This is working now, isn't it?

**Comment by TobiasNx** [comment]
yes
