### ISSUE TITLE
lookup with array-Path and *-Wildcard

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#96]
lookup with array-Path that has an *-Wildcard is not working. This could be due to this is an JSON-Array. 

[Example here](https://metafacture.org/playground/?data=%7B%0A%09%22animals%22%3A+%5B%0A%09%09%7B%0A%09%09%09%22name%22%3A+%22Jake%22%2C%0A%09%09%09%22animalGroup%22%3A+%22dog%22%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09%22name%22%3A+%22Blacky%22%2C%0A%09%09%09%22animalGroup%22%3A+%22parrot%22%0A%09%09%7D%0A%09%5D%0A%7D&flux=PG_DATA%0A%7Cas-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=put_map%28%22map%22%2C%0A%22dog%22%3A%22mammal%22%2C%0A%22parrot%22%3A%22bird%22%0A%09%29%0A%0Alookup%28%22animals%5B%5D.%2A.animalGroup%22%2C+%22map%22%29&active-editor=fix)
`
lookup("animals[].*.animalGroup", "map")`

**Comment by TobiasNx** [comment]
It seems that this is also an issue with string-arrays:

[See here](https://metafacture.org/playground/?data=%7B%0A%09%22bnimals%22%3A+%5B%22dog%22%2C+%22parrot%22%5D%0A%7D&flux=PG_DATA%0A%7Cas-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=put_map%28%22map%22%2C%0A%22dog%22%3A%22mammal%22%2C%0A%22parrot%22%3A%22bird%22%0A%09%29%0A%0Alookup%28%22bnimals%5B%5D.%2A%2C+%22map%22%29%0A&active-editor=fix)

**Comment by blackwinter** [comment]
This is working now, isn't it?

**Comment by TobiasNx** [comment]
Tested it. Yes, this seems to work now. +1

https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/lookupWithAsterisk
